// 一般的な目安値（100gあたり、g）です。食品成分表などをもとにした概算値であり、
// 実際の商品・調理法によって変動します。正確な値がわかる場合は数値を直接編集してください。
// unit / unitWeight がある食品は「1本」「1個」など単位でも入力できます（unitWeight は1単位あたりの重さの目安・g）。
export const FOOD_PRESETS = [
  // 主食
  { name: "白米（ご飯）", category: "主食", carbs: 37.1, protein: 2.5, fat: 0.3, fiber: 0.3 },
  { name: "玄米ご飯", category: "主食", carbs: 35.6, protein: 2.8, fat: 1.0, fiber: 1.4 },
  { name: "もち麦ごはん", category: "主食", carbs: 40.0, protein: 3.0, fat: 0.7, fiber: 3.0 },
  { name: "おかゆ（白がゆ）", category: "主食", carbs: 15.6, protein: 1.1, fat: 0.1, fiber: 0.1 },
  { name: "もち", category: "主食", carbs: 50.3, protein: 4.2, fat: 0.8, fiber: 0.5, unit: "個", unitWeight: 50 },
  { name: "おにぎり（具なし）", category: "主食", carbs: 37.1, protein: 2.5, fat: 0.3, fiber: 0.3, unit: "個", unitWeight: 100 },
  { name: "食パン", category: "主食", carbs: 46.7, protein: 9.3, fat: 4.4, fiber: 2.3, unit: "枚", unitWeight: 60 },
  { name: "ロールパン", category: "主食", carbs: 48.6, protein: 10.1, fat: 9.0, fiber: 2.0, unit: "個", unitWeight: 30 },
  { name: "クロワッサン", category: "主食", carbs: 43.9, protein: 7.9, fat: 26.8, fiber: 1.8, unit: "個", unitWeight: 40 },
  { name: "ベーグル", category: "主食", carbs: 54.6, protein: 9.6, fat: 2.0, fiber: 2.5, unit: "個", unitWeight: 90 },
  { name: "うどん（ゆで）", category: "主食", carbs: 21.6, protein: 2.6, fat: 0.4, fiber: 1.3 },
  { name: "そば（ゆで）", category: "主食", carbs: 26.0, protein: 4.8, fat: 1.0, fiber: 2.9 },
  { name: "そうめん（ゆで）", category: "主食", carbs: 25.8, protein: 3.5, fat: 0.4, fiber: 0.9 },
  { name: "スパゲッティ（ゆで）", category: "主食", carbs: 32.2, protein: 5.8, fat: 0.9, fiber: 3.0 },
  { name: "マカロニ・ペンネ（ゆで）", category: "主食", carbs: 30.3, protein: 5.8, fat: 0.9, fiber: 1.7 },
  { name: "中華麺（ゆで）", category: "主食", carbs: 29.2, protein: 4.9, fat: 0.6, fiber: 1.3 },
  { name: "焼きそば麺（蒸し）", category: "主食", carbs: 29.0, protein: 4.9, fat: 2.1, fiber: 2.6 },
  { name: "春雨（ゆで）", category: "主食", carbs: 19.9, protein: 0.1, fat: 0.2, fiber: 1.5 },
  { name: "オートミール（乾燥）", category: "主食", carbs: 69.1, protein: 13.7, fat: 5.7, fiber: 9.4 },
  { name: "コーンフレーク", category: "主食", carbs: 83.6, protein: 7.8, fat: 1.7, fiber: 2.4 },
  { name: "さつまいも", category: "主食", carbs: 29.7, protein: 1.2, fat: 0.2, fiber: 2.3 },
  { name: "じゃがいも", category: "主食", carbs: 17.6, protein: 1.6, fat: 0.1, fiber: 1.3, unit: "個", unitWeight: 150 },

  // 肉
  { name: "鶏むね肉（皮なし）", category: "肉", carbs: 0, protein: 23.3, fat: 1.9, fiber: 0, unit: "枚", unitWeight: 250 },
  { name: "鶏もも肉（皮なし）", category: "肉", carbs: 0, protein: 19.0, fat: 5.0, fiber: 0, unit: "枚", unitWeight: 250 },
  { name: "鶏ささみ", category: "肉", carbs: 0.1, protein: 23.9, fat: 0.8, fiber: 0, unit: "本", unitWeight: 40 },
  { name: "鶏手羽先", category: "肉", carbs: 0, protein: 17.4, fat: 16.2, fiber: 0, unit: "本", unitWeight: 60 },
  { name: "鶏手羽元", category: "肉", carbs: 0, protein: 18.2, fat: 12.8, fiber: 0, unit: "本", unitWeight: 60 },
  { name: "鶏皮", category: "肉", carbs: 0, protein: 9.4, fat: 41.6, fiber: 0 },
  { name: "豚ロース", category: "肉", carbs: 0.2, protein: 19.3, fat: 19.2, fiber: 0 },
  { name: "豚バラ", category: "肉", carbs: 0.1, protein: 14.4, fat: 34.6, fiber: 0 },
  { name: "豚肩ロース", category: "肉", carbs: 0.1, protein: 17.1, fat: 19.2, fiber: 0 },
  { name: "豚ひき肉", category: "肉", carbs: 0.1, protein: 17.7, fat: 17.2, fiber: 0 },
  { name: "牛もも肉", category: "肉", carbs: 0.5, protein: 21.3, fat: 13.3, fiber: 0 },
  { name: "牛サーロイン", category: "肉", carbs: 0.3, protein: 17.4, fat: 27.9, fiber: 0 },
  { name: "牛肩ロース", category: "肉", carbs: 0.2, protein: 16.2, fat: 26.4, fiber: 0 },
  { name: "牛ひき肉", category: "肉", carbs: 0.3, protein: 17.1, fat: 21.1, fiber: 0 },
  { name: "合いびき肉", category: "肉", carbs: 0.2, protein: 17.2, fat: 19.9, fiber: 0 },
  { name: "ラム肉", category: "肉", carbs: 0.2, protein: 19.3, fat: 15.5, fiber: 0 },
  { name: "ソーセージ", category: "肉", carbs: 3.0, protein: 13.2, fat: 28.5, fiber: 0, unit: "本", unitWeight: 20 },
  { name: "ベーコン", category: "肉", carbs: 0.3, protein: 12.9, fat: 39.1, fiber: 0, unit: "枚", unitWeight: 15 },
  { name: "ハム（ロース）", category: "肉", carbs: 1.3, protein: 16.5, fat: 13.9, fiber: 0, unit: "枚", unitWeight: 15 },
  { name: "生ハム", category: "肉", carbs: 0.5, protein: 25.7, fat: 16.6, fiber: 0, unit: "枚", unitWeight: 10 },
  { name: "唐揚げ", category: "肉", carbs: 8.0, protein: 16.0, fat: 12.0, fiber: 0.3, unit: "個", unitWeight: 30 },
  { name: "とんかつ", category: "肉", carbs: 10.2, protein: 17.2, fat: 27.2, fiber: 0.6, unit: "枚", unitWeight: 150 },
  { name: "ハンバーグ", category: "肉", carbs: 8.5, protein: 14.5, fat: 15.9, fiber: 0.6, unit: "個", unitWeight: 150 },
  { name: "餃子", category: "肉", carbs: 22.0, protein: 8.0, fat: 11.0, fiber: 1.5, unit: "個", unitWeight: 20 },

  // 魚介
  { name: "鮭（焼き）", category: "魚介", carbs: 0.1, protein: 29.1, fat: 8.4, fiber: 0, unit: "切れ", unitWeight: 80 },
  { name: "サバ（焼き）", category: "魚介", carbs: 0.3, protein: 26.2, fat: 16.6, fiber: 0, unit: "切れ", unitWeight: 80 },
  { name: "マグロ（赤身）", category: "魚介", carbs: 0.1, protein: 26.4, fat: 1.4, fiber: 0 },
  { name: "ぶり", category: "魚介", carbs: 0.3, protein: 21.4, fat: 17.6, fiber: 0, unit: "切れ", unitWeight: 80 },
  { name: "たい", category: "魚介", carbs: 0.1, protein: 20.6, fat: 5.8, fiber: 0 },
  { name: "あじ", category: "魚介", carbs: 0.1, protein: 19.7, fat: 4.5, fiber: 0, unit: "尾", unitWeight: 100 },
  { name: "いわし", category: "魚介", carbs: 0.2, protein: 19.8, fat: 9.2, fiber: 0, unit: "尾", unitWeight: 60 },
  { name: "さんま", category: "魚介", carbs: 0.1, protein: 18.1, fat: 24.6, fiber: 0, unit: "尾", unitWeight: 120 },
  { name: "たら", category: "魚介", carbs: 0.1, protein: 17.6, fat: 0.2, fiber: 0, unit: "切れ", unitWeight: 80 },
  { name: "ししゃも", category: "魚介", carbs: 0.2, protein: 21.0, fat: 8.1, fiber: 0, unit: "尾", unitWeight: 20 },
  { name: "うなぎ蒲焼", category: "魚介", carbs: 3.1, protein: 23.0, fat: 21.0, fiber: 0 },
  { name: "エビ", category: "魚介", carbs: 0.3, protein: 21.7, fat: 0.6, fiber: 0, unit: "尾", unitWeight: 15 },
  { name: "いか", category: "魚介", carbs: 0.1, protein: 17.9, fat: 0.8, fiber: 0 },
  { name: "たこ", category: "魚介", carbs: 0.1, protein: 16.4, fat: 0.7, fiber: 0 },
  { name: "ホタテ", category: "魚介", carbs: 1.5, protein: 13.5, fat: 0.3, fiber: 0, unit: "個", unitWeight: 30 },
  { name: "かに", category: "魚介", carbs: 0.1, protein: 13.9, fat: 0.3, fiber: 0 },
  { name: "しらす干し", category: "魚介", carbs: 0.1, protein: 24.5, fat: 2.1, fiber: 0 },
  { name: "ツナ缶（水煮）", category: "魚介", carbs: 0.1, protein: 16.0, fat: 0.7, fiber: 0 },
  { name: "ツナ缶（油漬け）", category: "魚介", carbs: 0.1, protein: 17.7, fat: 21.7, fiber: 0 },
  { name: "明太子", category: "魚介", carbs: 3.0, protein: 21.0, fat: 3.3, fiber: 0 },
  { name: "いくら", category: "魚介", carbs: 0.2, protein: 32.6, fat: 15.6, fiber: 0 },

  // 卵・乳製品
  { name: "卵（全卵）", category: "卵・乳製品", carbs: 0.3, protein: 12.2, fat: 10.2, fiber: 0, unit: "個", unitWeight: 50 },
  { name: "牛乳", category: "卵・乳製品", carbs: 4.8, protein: 3.3, fat: 3.8, fiber: 0, unit: "杯", unitWeight: 200 },
  { name: "ヨーグルト（無糖）", category: "卵・乳製品", carbs: 4.9, protein: 3.6, fat: 3.0, fiber: 0, unit: "カップ", unitWeight: 100 },
  { name: "チーズ（プロセス）", category: "卵・乳製品", carbs: 1.3, protein: 22.7, fat: 26.0, fiber: 0, unit: "個", unitWeight: 18 },
  { name: "モッツァレラチーズ", category: "卵・乳製品", carbs: 4.2, protein: 18.4, fat: 19.9, fiber: 0 },
  { name: "カッテージチーズ", category: "卵・乳製品", carbs: 1.9, protein: 13.3, fat: 4.5, fiber: 0 },
  { name: "生クリーム", category: "卵・乳製品", carbs: 3.1, protein: 1.9, fat: 45.0, fiber: 0 },
  { name: "バター", category: "卵・乳製品", carbs: 0.2, protein: 0.6, fat: 81.0, fiber: 0 },
  { name: "アイスクリーム", category: "卵・乳製品", carbs: 23.2, protein: 3.9, fat: 8.0, fiber: 0.1 },

  // 大豆製品
  { name: "豆乳", category: "大豆製品", carbs: 3.0, protein: 3.6, fat: 2.0, fiber: 0.2, unit: "杯", unitWeight: 200 },
  { name: "納豆", category: "大豆製品", carbs: 12.1, protein: 16.5, fat: 10.0, fiber: 6.7, unit: "パック", unitWeight: 45 },
  { name: "豆腐（木綿）", category: "大豆製品", carbs: 1.5, protein: 7.0, fat: 4.9, fiber: 0.4, unit: "丁", unitWeight: 300 },
  { name: "豆腐（絹ごし）", category: "大豆製品", carbs: 2.0, protein: 5.3, fat: 3.5, fiber: 0.3, unit: "丁", unitWeight: 300 },
  { name: "厚揚げ", category: "大豆製品", carbs: 0.9, protein: 10.7, fat: 11.3, fiber: 0.7, unit: "枚", unitWeight: 150 },
  { name: "油揚げ", category: "大豆製品", carbs: 0.4, protein: 18.6, fat: 33.1, fiber: 1.1, unit: "枚", unitWeight: 20 },
  { name: "がんもどき", category: "大豆製品", carbs: 2.0, protein: 15.3, fat: 17.8, fiber: 1.4, unit: "個", unitWeight: 80 },
  { name: "枝豆", category: "大豆製品", carbs: 8.8, protein: 11.7, fat: 6.2, fiber: 5.0 },
  { name: "おから", category: "大豆製品", carbs: 13.8, protein: 6.1, fat: 3.6, fiber: 11.5 },
  { name: "味噌", category: "大豆製品", carbs: 15.0, protein: 11.0, fat: 5.5, fiber: 4.0 },

  // 野菜
  { name: "ブロッコリー", category: "野菜", carbs: 5.2, protein: 4.3, fat: 0.5, fiber: 4.4 },
  { name: "ほうれん草", category: "野菜", carbs: 3.1, protein: 2.2, fat: 0.4, fiber: 2.8 },
  { name: "キャベツ", category: "野菜", carbs: 5.2, protein: 1.3, fat: 0.2, fiber: 1.8 },
  { name: "トマト", category: "野菜", carbs: 4.7, protein: 0.7, fat: 0.1, fiber: 1.0, unit: "個", unitWeight: 150 },
  { name: "にんじん", category: "野菜", carbs: 9.3, protein: 0.7, fat: 0.2, fiber: 2.8, unit: "本", unitWeight: 150 },
  { name: "アボカド", category: "野菜", carbs: 6.2, protein: 2.5, fat: 18.7, fiber: 5.6, unit: "個", unitWeight: 200 },
  { name: "玉ねぎ", category: "野菜", carbs: 8.8, protein: 1.0, fat: 0.1, fiber: 1.6, unit: "個", unitWeight: 200 },
  { name: "きゅうり", category: "野菜", carbs: 3.0, protein: 1.0, fat: 0.1, fiber: 1.1, unit: "本", unitWeight: 100 },
  { name: "なす", category: "野菜", carbs: 5.1, protein: 1.1, fat: 0.1, fiber: 2.2, unit: "本", unitWeight: 80 },
  { name: "ピーマン", category: "野菜", carbs: 5.1, protein: 0.9, fat: 0.2, fiber: 2.3, unit: "個", unitWeight: 35 },
  { name: "パプリカ", category: "野菜", carbs: 7.2, protein: 1.0, fat: 0.2, fiber: 1.6, unit: "個", unitWeight: 150 },
  { name: "レタス", category: "野菜", carbs: 2.8, protein: 0.6, fat: 0.1, fiber: 1.1 },
  { name: "大根", category: "野菜", carbs: 4.1, protein: 0.5, fat: 0.1, fiber: 1.4 },
  { name: "ごぼう", category: "野菜", carbs: 15.4, protein: 1.8, fat: 0.1, fiber: 5.7 },
  { name: "れんこん", category: "野菜", carbs: 15.5, protein: 1.9, fat: 0.1, fiber: 2.0 },
  { name: "かぼちゃ", category: "野菜", carbs: 20.6, protein: 1.9, fat: 0.3, fiber: 3.5 },
  { name: "とうもろこし", category: "野菜", carbs: 16.8, protein: 3.6, fat: 1.7, fiber: 3.0, unit: "本", unitWeight: 300 },
  { name: "もやし", category: "野菜", carbs: 2.6, protein: 1.7, fat: 0.1, fiber: 1.3 },
  { name: "白菜", category: "野菜", carbs: 3.2, protein: 0.8, fat: 0.1, fiber: 1.3 },
  { name: "小松菜", category: "野菜", carbs: 2.4, protein: 1.5, fat: 0.2, fiber: 1.9 },
  { name: "チンゲン菜", category: "野菜", carbs: 2.0, protein: 0.6, fat: 0.1, fiber: 1.2 },
  { name: "しいたけ", category: "野菜", carbs: 5.5, protein: 3.0, fat: 0.4, fiber: 4.9, unit: "個", unitWeight: 15 },
  { name: "しめじ", category: "野菜", carbs: 4.8, protein: 2.7, fat: 0.5, fiber: 3.5 },
  { name: "えのき", category: "野菜", carbs: 7.6, protein: 2.7, fat: 0.2, fiber: 3.9 },
  { name: "まいたけ", category: "野菜", carbs: 4.4, protein: 2.0, fat: 0.5, fiber: 3.5 },
  { name: "にんにく", category: "野菜", carbs: 27.5, protein: 6.4, fat: 0.9, fiber: 6.2, unit: "片", unitWeight: 5 },
  { name: "生姜", category: "野菜", carbs: 6.6, protein: 0.9, fat: 0.3, fiber: 2.1 },
  { name: "オクラ", category: "野菜", carbs: 6.6, protein: 2.1, fat: 0.2, fiber: 5.0, unit: "本", unitWeight: 10 },
  { name: "アスパラガス", category: "野菜", carbs: 3.9, protein: 2.6, fat: 0.2, fiber: 1.8, unit: "本", unitWeight: 20 },
  { name: "セロリ", category: "野菜", carbs: 3.6, protein: 0.4, fat: 0.1, fiber: 1.5 },
  { name: "ズッキーニ", category: "野菜", carbs: 2.8, protein: 1.3, fat: 0.1, fiber: 1.3 },

  // 果物
  { name: "バナナ", category: "果物", carbs: 22.5, protein: 1.1, fat: 0.2, fiber: 1.1, unit: "本", unitWeight: 100 },
  { name: "りんご", category: "果物", carbs: 14.6, protein: 0.2, fat: 0.1, fiber: 1.4, unit: "個", unitWeight: 250 },
  { name: "みかん", category: "果物", carbs: 11.0, protein: 0.7, fat: 0.1, fiber: 0.4, unit: "個", unitWeight: 100 },
  { name: "ぶどう", category: "果物", carbs: 15.7, protein: 0.4, fat: 0.1, fiber: 0.5 },
  { name: "いちご", category: "果物", carbs: 7.1, protein: 0.9, fat: 0.1, fiber: 1.4, unit: "粒", unitWeight: 15 },
  { name: "キウイ", category: "果物", carbs: 13.5, protein: 1.0, fat: 0.2, fiber: 2.6, unit: "個", unitWeight: 100 },
  { name: "パイナップル", category: "果物", carbs: 13.4, protein: 0.6, fat: 0.1, fiber: 1.2 },
  { name: "桃", category: "果物", carbs: 10.2, protein: 0.6, fat: 0.1, fiber: 1.3, unit: "個", unitWeight: 200 },
  { name: "梨", category: "果物", carbs: 11.3, protein: 0.3, fat: 0.1, fiber: 0.9, unit: "個", unitWeight: 300 },
  { name: "スイカ", category: "果物", carbs: 9.5, protein: 0.6, fat: 0.1, fiber: 0.3 },
  { name: "メロン", category: "果物", carbs: 9.8, protein: 1.0, fat: 0.1, fiber: 0.5 },
  { name: "柿", category: "果物", carbs: 15.9, protein: 0.4, fat: 0.2, fiber: 1.6, unit: "個", unitWeight: 180 },

  // 和食
  { name: "寿司（にぎり1貫）", category: "和食", carbs: 35.0, protein: 8.0, fat: 1.0, fiber: 0.3, unit: "貫", unitWeight: 25 },
  { name: "いなり寿司", category: "和食", carbs: 45.0, protein: 6.0, fat: 8.0, fiber: 1.0, unit: "個", unitWeight: 30 },
  { name: "ちらし寿司", category: "和食", carbs: 30.0, protein: 8.0, fat: 4.0, fiber: 1.0 },
  { name: "天丼（具のみ目安）", category: "和食", carbs: 20.0, protein: 8.0, fat: 15.0, fiber: 1.2 },
  { name: "だし巻き卵", category: "和食", carbs: 3.0, protein: 11.0, fat: 9.0, fiber: 0 },
  { name: "ひじきの煮物", category: "和食", carbs: 10.0, protein: 3.0, fat: 3.0, fiber: 5.0 },
  { name: "けんちん汁", category: "和食", carbs: 5.0, protein: 3.0, fat: 2.0, fiber: 1.5 },
  { name: "佃煮（こんぶ）", category: "和食", carbs: 40.0, protein: 4.0, fat: 0.5, fiber: 3.0 },
  { name: "お雑煮（もち込み目安）", category: "和食", carbs: 20.0, protein: 3.0, fat: 1.0, fiber: 0.5 },
  { name: "柏餅", category: "和食", carbs: 45.0, protein: 3.0, fat: 0.5, fiber: 1.5, unit: "個", unitWeight: 60 },
  { name: "桜餅", category: "和食", carbs: 45.0, protein: 3.0, fat: 0.3, fiber: 1.0, unit: "個", unitWeight: 50 },

  // 中華
  { name: "酢豚", category: "中華", carbs: 15.0, protein: 12.0, fat: 10.0, fiber: 1.0 },
  { name: "エビチリ", category: "中華", carbs: 8.0, protein: 12.0, fat: 8.0, fiber: 0.5 },
  { name: "青椒肉絲", category: "中華", carbs: 6.0, protein: 10.0, fat: 9.0, fiber: 1.5 },
  { name: "回鍋肉", category: "中華", carbs: 8.0, protein: 11.0, fat: 18.0, fiber: 1.5 },
  { name: "中華丼（具のみ目安）", category: "中華", carbs: 8.0, protein: 8.0, fat: 6.0, fiber: 1.0 },
  { name: "春巻き", category: "中華", carbs: 20.0, protein: 5.0, fat: 12.0, fiber: 1.5, unit: "本", unitWeight: 40 },
  { name: "小籠包", category: "中華", carbs: 20.0, protein: 8.0, fat: 8.0, fiber: 1.0, unit: "個", unitWeight: 20 },
  { name: "担々麺（麺・スープ込み目安）", category: "中華", carbs: 15.0, protein: 6.0, fat: 8.0, fiber: 1.0 },
  { name: "麻婆春雨", category: "中華", carbs: 12.0, protein: 6.0, fat: 7.0, fiber: 1.2 },
  { name: "杏仁豆腐", category: "中華", carbs: 15.0, protein: 3.0, fat: 3.0, fiber: 0.2 },

  // イタリアン
  { name: "マルゲリータピザ（1切れ目安）", category: "イタリアン", carbs: 24.0, protein: 10.0, fat: 9.0, fiber: 1.5, unit: "切れ", unitWeight: 100 },
  { name: "カルボナーラ", category: "イタリアン", carbs: 18.0, protein: 7.0, fat: 10.0, fiber: 1.0 },
  { name: "ペペロンチーノ", category: "イタリアン", carbs: 22.0, protein: 5.0, fat: 8.0, fiber: 1.5 },
  { name: "ミートソースパスタ", category: "イタリアン", carbs: 20.0, protein: 6.0, fat: 6.0, fiber: 1.5 },
  { name: "リゾット", category: "イタリアン", carbs: 20.0, protein: 4.0, fat: 5.0, fiber: 0.8 },
  { name: "ラザニア", category: "イタリアン", carbs: 15.0, protein: 8.0, fat: 9.0, fiber: 1.0 },
  { name: "ミネストローネ", category: "イタリアン", carbs: 6.0, protein: 2.0, fat: 2.0, fiber: 1.5 },
  { name: "カプレーゼ", category: "イタリアン", carbs: 3.0, protein: 8.0, fat: 12.0, fiber: 1.0 },
  { name: "ティラミス", category: "イタリアン", carbs: 30.0, protein: 5.0, fat: 20.0, fiber: 0.5 },
  { name: "ジェラート", category: "イタリアン", carbs: 25.0, protein: 4.0, fat: 8.0, fiber: 0 },

  // フレンチ
  { name: "キッシュ", category: "フレンチ", carbs: 15.0, protein: 9.0, fat: 18.0, fiber: 1.0 },
  { name: "ラタトゥイユ", category: "フレンチ", carbs: 6.0, protein: 1.5, fat: 3.0, fiber: 2.0 },
  { name: "グラタン", category: "フレンチ", carbs: 12.0, protein: 7.0, fat: 10.0, fiber: 0.8 },
  { name: "コンソメスープ", category: "フレンチ", carbs: 2.0, protein: 1.0, fat: 0.5, fiber: 0.2 },
  { name: "クレープ（甘め）", category: "フレンチ", carbs: 30.0, protein: 6.0, fat: 8.0, fiber: 0.8, unit: "枚", unitWeight: 80 },
  { name: "クロックムッシュ", category: "フレンチ", carbs: 25.0, protein: 15.0, fat: 18.0, fiber: 1.5 },
  { name: "ブイヤベース", category: "フレンチ", carbs: 4.0, protein: 10.0, fat: 4.0, fiber: 0.5 },
  { name: "クリームブリュレ", category: "フレンチ", carbs: 20.0, protein: 4.0, fat: 15.0, fiber: 0 },

  // ドイツ料理
  { name: "ザワークラウト", category: "ドイツ料理", carbs: 4.0, protein: 1.0, fat: 0.2, fiber: 2.5 },
  { name: "プレッツェル", category: "ドイツ料理", carbs: 55.0, protein: 10.0, fat: 4.0, fiber: 2.5, unit: "個", unitWeight: 80 },
  { name: "アイスバイン", category: "ドイツ料理", carbs: 0.5, protein: 22.0, fat: 15.0, fiber: 0 },
  { name: "ジャーマンポテト", category: "ドイツ料理", carbs: 15.0, protein: 2.0, fat: 6.0, fiber: 1.5 },
  { name: "シュニッツェル", category: "ドイツ料理", carbs: 12.0, protein: 20.0, fat: 15.0, fiber: 0.8 },
  { name: "ブラートヴルスト", category: "ドイツ料理", carbs: 2.0, protein: 13.0, fat: 25.0, fiber: 0, unit: "本", unitWeight: 100 },

  // 料理・その他
  { name: "味噌汁（具なし目安）", category: "料理・その他", carbs: 3.0, protein: 2.0, fat: 1.0, fiber: 0.5 },
  { name: "カレー（ルーのみ目安）", category: "料理・その他", carbs: 12.0, protein: 2.0, fat: 8.0, fiber: 1.0 },
  { name: "天ぷら（野菜）", category: "料理・その他", carbs: 15.0, protein: 3.0, fat: 15.0, fiber: 1.5 },
  { name: "親子丼（具のみ目安）", category: "料理・その他", carbs: 5.0, protein: 12.0, fat: 8.0, fiber: 0.5 },
  { name: "牛丼（具のみ目安）", category: "料理・その他", carbs: 6.0, protein: 10.0, fat: 12.0, fiber: 0.5 },
  { name: "麻婆豆腐", category: "料理・その他", carbs: 4.5, protein: 8.0, fat: 9.0, fiber: 0.8 },
  { name: "肉じゃが", category: "料理・その他", carbs: 10.0, protein: 4.5, fat: 3.5, fiber: 1.3 },
  { name: "きんぴらごぼう", category: "料理・その他", carbs: 12.0, protein: 2.0, fat: 3.5, fiber: 4.0 },
  { name: "ポテトサラダ", category: "料理・その他", carbs: 12.0, protein: 1.8, fat: 8.0, fiber: 1.2 },
  { name: "お好み焼き", category: "料理・その他", carbs: 20.0, protein: 7.5, fat: 10.0, fiber: 1.8 },
  { name: "たこ焼き", category: "料理・その他", carbs: 24.0, protein: 6.0, fat: 8.0, fiber: 1.0, unit: "個", unitWeight: 20 },
  { name: "焼き鳥（塩・もも）", category: "料理・その他", carbs: 0.5, protein: 18.0, fat: 10.0, fiber: 0, unit: "本", unitWeight: 50 },
  { name: "おでん（具材目安）", category: "料理・その他", carbs: 6.0, protein: 6.0, fat: 3.0, fiber: 1.0 },
  { name: "チャーハン", category: "料理・その他", carbs: 32.0, protein: 7.0, fat: 8.5, fiber: 0.8 },
  { name: "オムライス", category: "料理・その他", carbs: 25.0, protein: 8.5, fat: 10.0, fiber: 0.5 },
  { name: "ハンバーガー", category: "料理・その他", carbs: 30.0, protein: 13.0, fat: 12.0, fiber: 1.5, unit: "個", unitWeight: 250 },

  // 飲み物
  { name: "オレンジジュース", category: "飲み物", carbs: 10.7, protein: 0.7, fat: 0.1, fiber: 0.2 },
  { name: "スポーツドリンク", category: "飲み物", carbs: 4.3, protein: 0, fat: 0, fiber: 0 },
  { name: "甘酒", category: "飲み物", carbs: 18.3, protein: 1.7, fat: 0.1, fiber: 0.4 },
  { name: "ココア（調整済み飲料目安）", category: "飲み物", carbs: 10.5, protein: 1.9, fat: 1.9, fiber: 0.5 },
  { name: "プロテインパウダー（目安/100g）", category: "飲み物", carbs: 7.0, protein: 75.0, fat: 5.0, fiber: 1.0 },

  // 調味料
  { name: "醤油", category: "調味料", carbs: 10.1, protein: 7.7, fat: 0, fiber: 0 },
  { name: "みりん", category: "調味料", carbs: 43.2, protein: 0.1, fat: 0, fiber: 0 },
  { name: "砂糖", category: "調味料", carbs: 99.3, protein: 0, fat: 0, fiber: 0 },
  { name: "マヨネーズ", category: "調味料", carbs: 3.6, protein: 1.4, fat: 76.0, fiber: 0 },
  { name: "ケチャップ", category: "調味料", carbs: 25.6, protein: 1.6, fat: 0.2, fiber: 0.5 },
  { name: "オリーブオイル", category: "調味料", carbs: 0, protein: 0, fat: 100.0, fiber: 0 },
  { name: "ごま油", category: "調味料", carbs: 0, protein: 0, fat: 100.0, fiber: 0 },
  { name: "ポン酢", category: "調味料", carbs: 8.1, protein: 2.6, fat: 0, fiber: 0.2 },

  // お菓子・デザート
  { name: "ポテトチップス", category: "お菓子・デザート", carbs: 50.5, protein: 4.7, fat: 35.2, fiber: 4.2 },
  { name: "板チョコレート", category: "お菓子・デザート", carbs: 55.0, protein: 6.0, fat: 34.0, fiber: 3.5 },
  { name: "クッキー", category: "お菓子・デザート", carbs: 63.9, protein: 5.9, fat: 27.6, fiber: 1.8 },
  { name: "どら焼き", category: "お菓子・デザート", carbs: 55.6, protein: 6.0, fat: 3.2, fiber: 1.5, unit: "個", unitWeight: 80 },
  { name: "大福", category: "お菓子・デザート", carbs: 50.0, protein: 4.5, fat: 0.5, fiber: 1.8, unit: "個", unitWeight: 60 },
  { name: "プリン", category: "お菓子・デザート", carbs: 14.7, protein: 5.5, fat: 5.5, fiber: 0, unit: "個", unitWeight: 90 },
  { name: "ゼリー（フルーツ）", category: "お菓子・デザート", carbs: 16.0, protein: 1.5, fat: 0.1, fiber: 0.3 },
  { name: "せんべい（醤油味）", category: "お菓子・デザート", carbs: 83.9, protein: 7.3, fat: 1.0, fiber: 0.6, unit: "枚", unitWeight: 15 },

  // その他
  { name: "アーモンド", category: "その他", carbs: 20.9, protein: 19.6, fat: 51.8, fiber: 10.1 }
];

export const FOOD_CATEGORIES = ["すべて", ...Array.from(new Set(FOOD_PRESETS.map((f) => f.category)))];
