// 一般的な目安値（100gあたり、g）です。食品成分表などをもとにした概算値であり、
// 実際の商品・調理法によって変動します。正確な値がわかる場合は数値を直接編集してください。
export const FOOD_PRESETS = [
  { name: "白米（ご飯）", category: "主食", carbs: 37.1, protein: 2.5, fat: 0.3, fiber: 0.3 },
  { name: "玄米ご飯", category: "主食", carbs: 35.6, protein: 2.8, fat: 1.0, fiber: 1.4 },
  { name: "食パン", category: "主食", carbs: 46.7, protein: 9.3, fat: 4.4, fiber: 2.3 },
  { name: "うどん（ゆで）", category: "主食", carbs: 21.6, protein: 2.6, fat: 0.4, fiber: 1.3 },
  { name: "そば（ゆで）", category: "主食", carbs: 26.0, protein: 4.8, fat: 1.0, fiber: 2.9 },
  { name: "スパゲッティ（ゆで）", category: "主食", carbs: 32.2, protein: 5.8, fat: 0.9, fiber: 3.0 },
  { name: "中華麺（ゆで）", category: "主食", carbs: 29.2, protein: 4.9, fat: 0.6, fiber: 1.3 },
  { name: "オートミール（乾燥）", category: "主食", carbs: 69.1, protein: 13.7, fat: 5.7, fiber: 9.4 },
  { name: "さつまいも", category: "主食", carbs: 29.7, protein: 1.2, fat: 0.2, fiber: 2.3 },
  { name: "じゃがいも", category: "主食", carbs: 17.6, protein: 1.6, fat: 0.1, fiber: 1.3 },
  { name: "鶏むね肉（皮なし）", category: "肉", carbs: 0, protein: 23.3, fat: 1.9, fiber: 0 },
  { name: "鶏もも肉（皮なし）", category: "肉", carbs: 0, protein: 19.0, fat: 5.0, fiber: 0 },
  { name: "鶏ささみ", category: "肉", carbs: 0.1, protein: 23.9, fat: 0.8, fiber: 0 },
  { name: "豚ロース", category: "肉", carbs: 0.2, protein: 19.3, fat: 19.2, fiber: 0 },
  { name: "豚バラ", category: "肉", carbs: 0.1, protein: 14.4, fat: 34.6, fiber: 0 },
  { name: "牛もも肉", category: "肉", carbs: 0.5, protein: 21.3, fat: 13.3, fiber: 0 },
  { name: "牛サーロイン", category: "肉", carbs: 0.3, protein: 17.4, fat: 27.9, fiber: 0 },
  { name: "唐揚げ", category: "肉", carbs: 8.0, protein: 16.0, fat: 12.0, fiber: 0.3 },
  { name: "餃子", category: "肉", carbs: 22.0, protein: 8.0, fat: 11.0, fiber: 1.5 },
  { name: "鮭（焼き）", category: "魚介", carbs: 0.1, protein: 29.1, fat: 8.4, fiber: 0 },
  { name: "サバ（焼き）", category: "魚介", carbs: 0.3, protein: 26.2, fat: 16.6, fiber: 0 },
  { name: "マグロ（赤身）", category: "魚介", carbs: 0.1, protein: 26.4, fat: 1.4, fiber: 0 },
  { name: "エビ", category: "魚介", carbs: 0.3, protein: 21.7, fat: 0.6, fiber: 0 },
  { name: "卵（全卵）", category: "卵・乳製品", carbs: 0.3, protein: 12.2, fat: 10.2, fiber: 0 },
  { name: "牛乳", category: "卵・乳製品", carbs: 4.8, protein: 3.3, fat: 3.8, fiber: 0 },
  { name: "ヨーグルト（無糖）", category: "卵・乳製品", carbs: 4.9, protein: 3.6, fat: 3.0, fiber: 0 },
  { name: "チーズ（プロセス）", category: "卵・乳製品", carbs: 1.3, protein: 22.7, fat: 26.0, fiber: 0 },
  { name: "豆乳", category: "大豆製品", carbs: 3.0, protein: 3.6, fat: 2.0, fiber: 0.2 },
  { name: "納豆", category: "大豆製品", carbs: 12.1, protein: 16.5, fat: 10.0, fiber: 6.7 },
  { name: "豆腐（木綿）", category: "大豆製品", carbs: 1.5, protein: 7.0, fat: 4.9, fiber: 0.4 },
  { name: "豆腐（絹ごし）", category: "大豆製品", carbs: 2.0, protein: 5.3, fat: 3.5, fiber: 0.3 },
  { name: "味噌", category: "大豆製品", carbs: 15.0, protein: 11.0, fat: 5.5, fiber: 4.0 },
  { name: "ブロッコリー", category: "野菜", carbs: 5.2, protein: 4.3, fat: 0.5, fiber: 4.4 },
  { name: "ほうれん草", category: "野菜", carbs: 3.1, protein: 2.2, fat: 0.4, fiber: 2.8 },
  { name: "キャベツ", category: "野菜", carbs: 5.2, protein: 1.3, fat: 0.2, fiber: 1.8 },
  { name: "トマト", category: "野菜", carbs: 4.7, protein: 0.7, fat: 0.1, fiber: 1.0 },
  { name: "にんじん", category: "野菜", carbs: 9.3, protein: 0.7, fat: 0.2, fiber: 2.8 },
  { name: "アボカド", category: "野菜", carbs: 6.2, protein: 2.5, fat: 18.7, fiber: 5.6 },
  { name: "味噌汁（具なし目安）", category: "料理・その他", carbs: 3.0, protein: 2.0, fat: 1.0, fiber: 0.5 },
  { name: "カレー（ルーのみ目安）", category: "料理・その他", carbs: 12.0, protein: 2.0, fat: 8.0, fiber: 1.0 },
  { name: "天ぷら（野菜）", category: "料理・その他", carbs: 15.0, protein: 3.0, fat: 15.0, fiber: 1.5 },
  { name: "バナナ", category: "果物", carbs: 22.5, protein: 1.1, fat: 0.2, fiber: 1.1 },
  { name: "りんご", category: "果物", carbs: 14.6, protein: 0.2, fat: 0.1, fiber: 1.4 },
  { name: "みかん", category: "果物", carbs: 11.0, protein: 0.7, fat: 0.1, fiber: 0.4 },
  { name: "アーモンド", category: "その他", carbs: 20.9, protein: 19.6, fat: 51.8, fiber: 10.1 }
];

export const FOOD_CATEGORIES = ["すべて", ...Array.from(new Set(FOOD_PRESETS.map((f) => f.category)))];
