#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "docs", "records", "修正の記録-No.010-連絡の札を戻す.md")
BAR = "─" * 40


def main():
  L = []

  def s(t=""):
    L.append(t)

  s(BAR)
  s("　修正の記録　No.010")
  s(BAR)
  s("　見つけた日　　2026年9月13日")
  s()
  s("　見つけた人　　Code（Opus）")
  s("　　　　　　　　★見つけ方　★A3（10役職 × 12画面 ＝ 120通り）を 回した。")
  s("　　　　　　　　　★食い違い 33通り。★うち 3通りが「漏れ」──")
  s("　　　　　　　　　★見本は「だめ」、★実装は「出す」。")
  s()
  s("　何が起きたか　★学科長に、★連絡の タブが 出て いた。")
  s("　　　　　　　　★★学科長の できこと（★lib/opsPerms.js）──")
  s("　　　　　　　　　　meibo・sched_all・gyoji・shukketsu・koma")
  s("　　　　　　　　★★`renraku_all` も `monka_write` も 持って いない。")
  s("　　　　　　　　★★それでも 出て いたのは、★名前の ちから（role）で")
  s("　　　　　　　　　★決めて いた ため ── `BY_ROLE[\"admin\"]` に threads。")
  s()
  s("　　　　　　　　★★見本と 実装は 食い違って いない。★両方 とも")
  s("　　　　　　　　　★学科長は `renraku_all` を 持たない と 書いて ある。")
  s("　　　　　　　　　★期待表の 誤り（★No.005）とは ちがう 形。")
  s()
  s("　範囲　　　　　★画面の 出し分け だけ。★台帳の 決まりでは ない。")
  s("　　　　　　　　★★役職を **持たない** 方の 経路。")
  s("　　　　　　　　　★役職を 持つ 方は、★2026-09-13 の 直し（opsFixOn）で")
  s("　　　　　　　　　★もう できことで 決まって いる。")
  s()
  s("　原因　　　　　★同じ 決めごとが 2つの 軸に あった ──")
  s("　　　　　　　　　★見本　… ★できこと（perms）")
  s("　　　　　　　　　★実装　… ★名前の ちから（role）")
  s("　　　　　　　　★★A13（できことへ 移す）の 前だから 残って いる ぶん。")
  s(BAR)
  s("　★直した日　　　2026年9月13日　★★ただし **戻しました**")
  s(BAR)
  s()
  s("　　直した人　　　Code（Opus）")
  s()
  s("　　したこと　　　① `BY_ROLE[\"admin\"]` から threads を 外した")
  s("　　　　　　　　　② 数え直した")
  s("　　　　　　　　　③ **戻した**")
  s()
  s("　★★なぜ 戻したか")
  s()
  s("　　★外した ときの 数 ──")
  s("　　　　食い違い　33 → **35**（★増えた）")
  s("　　　　漏れ　　　 3 → **2**（★減った）")
  s()
  s("　　★★漏れは 1つ 減った。★けれど 拒否が 3つ 増えた ──")
  s("　　　　連絡: 副学長・事務長・学部長 が **出なく なった**")
  s()
  s("　　★★この 3つは `renraku_all` を **持って いる**。")
  s("　　★★止める 理由が ない。★仕事が 止まる。")
  s()
  s("　　★★§7-3 で 避けた ことと 同じ 形 ──")
  s("　　　「★穴は 閉じます。★けれど、★その 方の 仕事も 止まります」")
  s()
  s("　　★★坂本さんの お決め（2026-09-13）──")
  s("　　　★㋐ 戻す。★学科長の 漏れは A13 まで **わざと 開けた まま**。")
  s()
  s("　　確かめた方法　★python3 tools/perm_matrix_120.py")
  s("　　　　　　　　　★戻す 前　食い違い 35／漏れ 2")
  s("　　　　　　　　　★戻した 後　食い違い **33**／漏れ **3**（★元の 数）")
  s("　　　　　　　　　★★できことで 決めたら　食い違い **0**／漏れ **0**")
  s()
  s(BAR)
  s("　★★わざと 開けた まま に する もの")
  s(BAR)
  s()
  s("　★学科長 × 連絡　── ★タブが 出ます。★A13 まで そのまま。")
  s()
  s("　★★どこまで 分かって いるか")
  s("　　★出る のは **札**（タブ）です。")
  s("　　★★書く ときの 守りは 別に あります ──")
  s("　　　★`org_messages` の 決まり 2本（org_messages_insert／_select）。")
  s("　　★★★ただし、★その 2本は `renraku_all` を **見て いません**。")
  s("　　　★`auth.uid()` と `assignments` を 見て います。")
  s("　　　★★だから「見えるだけ だから 安全」とは **申しません**。")
  s("　　　★★確かめて いません。")
  s("　　★一覧 docs/reports/2026-09-13-role-dependent-policies.md")
  s()
  s("　★★A13 で 閉じます。★そのとき、★この 記録に 続きを 書きます。")
  s()
  s(BAR)
  s("　★この 記録の 出どころ")
  s(BAR)
  s()
  s("　　docs/reports/2026-09-13-A3-120通り.md")
  s("　　docs/reports/2026-09-13-role-dependent-policies.md")
  s("　　lib/opsShell.js（BY_ROLE の 注記）")
  s("　　tools/perm_matrix_120.py")
  s()
  s("　★この 紙自身も、★tools/write_record_010.py が 書き出して います。")
  s(BAR)

  with open(OUT, "w", encoding="utf-8") as f:
    f.write("\n".join(L) + "\n")
  print(os.path.relpath(OUT, ROOT) + "  全%d行" % len(L))
  return 0


if __name__ == "__main__":
  sys.exit(main())
