-- ★★★土台 ── 索引（しばりが 作る ものは 除く）
-- ★裁定175 ㋐。★2026-09-23 の 本番（xxjtplvpcneksrofkjmf）の 形を 機械で 書き出した もの。
-- ★★本番には 当てません。★「すでに 当たって いる」と 記録するだけ です。

-- ★85 本

create index if not exists account_deletions_at_idx ON public.account_deletions USING btree (deleted_at DESC);
create index if not exists age_answer_changes_user_idx ON public.age_answer_changes USING btree (user_id, changed_at DESC);
create index if not exists application_messages_app_idx ON public.application_messages USING btree (application_id, created_at);
create index if not exists applications_applicant_idx ON public.applications USING btree (applicant_user_id, created_at DESC);
create index if not exists applications_posting_idx ON public.applications USING btree (posting_id, created_at);
create index if not exists article_progress_due_idx ON public.article_progress USING btree (user_id, next_due_at);
create unique index if not exists assignments_active_unique ON public.assignments USING btree (org_id, teacher_id, student_id) WHERE (ended_at IS NULL);
create index if not exists code_attempts_at ON public.code_attempts USING btree (at);
create index if not exists code_attempts_code_at ON public.code_attempts USING btree (code_hash, at DESC);
create index if not exists code_attempts_ip_at ON public.code_attempts USING btree (ip_hash, at DESC);
create index if not exists cohort_changes_user_idx ON public.cohort_changes USING btree (user_id, changed_at DESC);
create index if not exists consent_records_user_purpose_idx ON public.consent_records USING btree (user_id, purpose_key, granted_at DESC);
create index if not exists contract_owner_log_org_idx ON public.contract_owner_log USING btree (org_id, changed_at DESC);
create index if not exists cycle_periods_user_start_idx ON public.cycle_periods USING btree (user_id, start_date DESC);
create unique index if not exists enrollments_student_number_uniq ON public.enrollments USING btree (org_id, student_number) WHERE (student_number IS NOT NULL);
create index if not exists events_name_at_idx ON public.events USING btree (name, at DESC);
create index if not exists events_user_at_idx ON public.events USING btree (user_id, at DESC);
create index if not exists export_log_org_idx ON public.export_log USING btree (org_id, created_at DESC);
create index if not exists guardian_consents_user_idx ON public.guardian_consents USING btree (user_id, org_id);
create index if not exists item_acquisitions_user_date_idx ON public.item_acquisitions USING btree (user_id, acquired_on DESC, created_at DESC);
create index if not exists koen_kids_koen_idx ON public.koen_kids USING btree (koen_id) WHERE (left_at IS NULL);
create unique index if not exists koen_members_user_unique ON public.koen_members USING btree (koen_id, user_id) WHERE (user_id IS NOT NULL);
create index if not exists lesson_preset_targets_teacher_idx ON public.lesson_preset_targets USING btree (org_id, teacher_id);
create unique index if not exists lesson_presets_org_name_idx ON public.lesson_presets USING btree (org_id, name);
create index if not exists lesson_rounds_org_idx ON public.lesson_rounds USING btree (org_id, status);
create index if not exists matching_cuts_target_idx ON public.matching_cuts USING btree (target_user_id, user_id);
create index if not exists matching_cuts_user_idx ON public.matching_cuts USING btree (user_id, target_user_id);
create index if not exists matching_reports_reporter_idx ON public.matching_reports USING btree (reporter_user_id, created_at DESC);
create index if not exists matching_reports_target_idx ON public.matching_reports USING btree (target_user_id, outcome);
create index if not exists memberships_org_grade_idx ON public.memberships USING btree (org_id, grade_label) WHERE (grade_label IS NOT NULL);
create index if not exists memberships_post_idx ON public.memberships USING btree (post_id) WHERE (post_id IS NOT NULL);
create index if not exists minor_billing_consents_user_idx ON public.minor_billing_consents USING btree (user_id, declared_at DESC);
create index if not exists monka_read_log_org_viewed_idx ON public.monka_read_log USING btree (org_id, viewed_at DESC);
create index if not exists monka_read_log_target_idx ON public.monka_read_log USING btree (target_monka_id, viewed_at DESC);
create unique index if not exists my_periods_uniq_org ON public.my_periods USING btree (user_id, org_id, ord) WHERE (org_id IS NOT NULL);
create unique index if not exists my_periods_uniq_personal ON public.my_periods USING btree (user_id, ord) WHERE (org_id IS NULL);
create index if not exists my_periods_user ON public.my_periods USING btree (user_id, ord);
create index if not exists my_periods_user_org_idx ON public.my_periods USING btree (user_id, org_id);
create index if not exists my_timetable_user ON public.my_timetable USING btree (user_id, weekday);
create index if not exists notes_body_trgm_idx ON public.notes USING gin (body gin_trgm_ops) WHERE (deleted_at IS NULL);
create index if not exists notes_user_kind_updated_idx ON public.notes USING btree (user_id, kind, updated_at DESC) WHERE (deleted_at IS NULL);
create index if not exists notes_user_repertoire_idx ON public.notes USING btree (user_id, repertoire_name) WHERE (repertoire_name IS NOT NULL);
create index if not exists notice_targets_batch_idx ON public.notice_targets USING btree (batch_id);
create index if not exists notice_targets_user_idx ON public.notice_targets USING btree (user_id);
create index if not exists ops_alerts_unnotified ON public.ops_alerts USING btree (created_at) WHERE (notified_at IS NULL);
create index if not exists ops_audit_org_idx ON public.ops_audit_log USING btree (org_id, created_at DESC);
create index if not exists org_billing_org_id_created_at_idx ON public.org_billing USING btree (org_id, created_at DESC);
create unique index if not exists org_billing_org_unique ON public.org_billing USING btree (org_id);
create index if not exists org_billing_log_org_idx ON public.org_billing_log USING btree (org_id, created_at DESC);
create index if not exists org_divisions_org_idx ON public.org_divisions USING btree (org_id, kind, sort_order);
create index if not exists org_divisions_parent_idx ON public.org_divisions USING btree (parent_id);
create index if not exists org_event_participants_user_idx ON public.org_event_participants USING btree (user_id);
create index if not exists org_events_org_date_idx ON public.org_events USING btree (org_id, event_date);
create index if not exists org_message_reads_org_idx ON public.org_message_reads USING btree (org_id, teacher_id, read_at DESC);
create index if not exists org_messages_created_idx ON public.org_messages USING btree (created_at);
create index if not exists org_messages_org_teacher_idx ON public.org_messages USING btree (org_id, teacher_id, created_at DESC) WHERE (withdrawn_at IS NULL);
create index if not exists org_post_perm_log_org_idx ON public.org_post_perm_log USING btree (org_id, changed_at DESC);
create index if not exists org_post_perm_log_post_idx ON public.org_post_perm_log USING btree (post_id, changed_at DESC);
create index if not exists org_posts_org_idx ON public.org_posts USING btree (org_id, sort_order, name);
create index if not exists page_inquiries_owner_idx ON public.page_inquiries USING btree (owner_user_id, created_at DESC);
create unique index if not exists payment_records_session_uniq ON public.payment_records USING btree (stripe_session_id) WHERE (stripe_session_id IS NOT NULL);
create unique index if not exists payment_records_sub_uniq ON public.payment_records USING btree (stripe_subscription_id) WHERE (stripe_subscription_id IS NOT NULL);
create index if not exists performance_results_user ON public.performance_results USING btree (user_id);
create index if not exists performances_user_date ON public.performances USING btree (user_id, performed_on);
create index if not exists performances_user_kind_date ON public.performances USING btree (user_id, kind, performed_on);
create index if not exists period_markers_user_date_idx ON public.period_markers USING btree (user_id, marked_on DESC);
create index if not exists portfolio_entries_user_idx ON public.portfolio_entries USING btree (user_id, kind, sort_order);
create index if not exists portfolio_recordings_user_idx ON public.portfolio_recordings USING btree (user_id, sort_order);
create index if not exists post_change_log_org_at_idx ON public.post_change_log USING btree (org_id, changed_at DESC);
create index if not exists post_change_log_target_idx ON public.post_change_log USING btree (target_user_id, changed_at DESC);
create index if not exists postings_expires_idx ON public.postings USING btree (org_id, status, expires_at);
create index if not exists postings_org_status_idx ON public.postings USING btree (org_id, status, created_at DESC);
create index if not exists postings_owner_idx ON public.postings USING btree (owner_user_id);
create index if not exists profiles_deleted_at_idx ON public.profiles USING btree (deleted_at) WHERE (deleted_at IS NOT NULL);
create index if not exists purchases_active_idx ON public.purchases USING btree (user_id, ends_at);
create unique index if not exists purchases_payment_intent_key ON public.purchases USING btree (stripe_payment_intent) WHERE (stripe_payment_intent IS NOT NULL);
create index if not exists purchases_user_idx ON public.purchases USING btree (user_id);
create index if not exists roster_drafts_org_idx ON public.roster_drafts USING btree (org_id, imported_at DESC);
create index if not exists spc_user_active_idx ON public.student_price_consents USING btree (user_id) WHERE (withdrawn_at IS NULL);
create index if not exists subscription_items_user_idx ON public.subscription_items USING btree (user_id) WHERE (removed_at IS NULL);
create index if not exists subscriptions_tier_idx ON public.subscriptions USING btree (tier);
create index if not exists teacher_invitations_monka_idx ON public.teacher_invitations USING btree (monka_teacher_id);
create unique index if not exists teacher_invitations_named_open_uniq ON public.teacher_invitations USING btree (monka_teacher_id, target_user_id) WHERE ((kind = 'named'::text) AND (used_at IS NULL));
create unique index if not exists teacher_student_links_active_pair_idx ON public.teacher_student_links USING btree (teacher_id, student_id) WHERE (status = 'active'::text);
create index if not exists user_notices_user_idx ON public.user_notices USING btree (user_id);
