-- ★★★土台 ── 権限（GRANT）
-- ★裁定175 ㋐。★2026-09-23 の 本番（xxjtplvpcneksrofkjmf）の 形を 機械で 書き出した もの。
-- ★★本番には 当てません。★「すでに 当たって いる」と 記録するだけ です。

-- ★★★取り上げてから 与えます（台帳 …… 列ごとの GRANT は、★表ごとの GRANT に 負けます）。
-- ★★ここが 抜けると、★いま 直して いる 穴が 試しで 再び 起きません。

-- ★★★1 表と 連番
revoke all on public.account_deletions from anon, authenticated, service_role, postgres;
grant delete, insert, maintain, select, update on public.account_deletions to authenticated;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.account_deletions to postgres;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.account_deletions to service_role;
revoke all on public.age_answer_changes from anon, authenticated, service_role, postgres;
grant delete, insert, maintain, select, update on public.age_answer_changes to authenticated;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.age_answer_changes to postgres;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.age_answer_changes to service_role;
revoke all on public.app_secrets from anon, authenticated, service_role, postgres;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.app_secrets to postgres;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.app_secrets to service_role;
revoke all on public.application_messages from anon, authenticated, service_role, postgres;
grant delete on public.application_messages to authenticated;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.application_messages to postgres;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.application_messages to service_role;
revoke all on public.applications from anon, authenticated, service_role, postgres;
grant delete on public.applications to authenticated;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.applications to postgres;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.applications to service_role;
revoke all on public.article_notes from anon, authenticated, service_role, postgres;
grant delete, insert, maintain, select, update on public.article_notes to authenticated;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.article_notes to postgres;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.article_notes to service_role;
revoke all on public.article_progress from anon, authenticated, service_role, postgres;
grant delete, insert, maintain, select, update on public.article_progress to authenticated;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.article_progress to postgres;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.article_progress to service_role;
revoke all on public.assignments from anon, authenticated, service_role, postgres;
grant insert, maintain, select on public.assignments to authenticated;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.assignments to postgres;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.assignments to service_role;
revoke all on public.calendar_tokens from anon, authenticated, service_role, postgres;
grant select on public.calendar_tokens to authenticated;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.calendar_tokens to postgres;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.calendar_tokens to service_role;
revoke all on public.chapter_state from anon, authenticated, service_role, postgres;
grant delete, insert, maintain, select, update on public.chapter_state to authenticated;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.chapter_state to postgres;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.chapter_state to service_role;
revoke all on public.character_inventory from anon, authenticated, service_role, postgres;
grant select on public.character_inventory to authenticated;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.character_inventory to postgres;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.character_inventory to service_role;
revoke all on public.code_attempts from anon, authenticated, service_role, postgres;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.code_attempts to postgres;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.code_attempts to service_role;
revoke all on public.cohort_changes from anon, authenticated, service_role, postgres;
grant delete, insert, maintain, select, update on public.cohort_changes to authenticated;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.cohort_changes to postgres;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.cohort_changes to service_role;
revoke all on public.consent_records from anon, authenticated, service_role, postgres;
grant insert, maintain, select on public.consent_records to authenticated;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.consent_records to postgres;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.consent_records to service_role;
revoke all on public.contract_owner_log from anon, authenticated, service_role, postgres;
grant select on public.contract_owner_log to authenticated;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.contract_owner_log to postgres;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.contract_owner_log to service_role;
revoke all on public.cycle_periods from anon, authenticated, service_role, postgres;
grant delete, insert, maintain, select, update on public.cycle_periods to authenticated;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.cycle_periods to postgres;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.cycle_periods to service_role;
revoke all on public.email_change_log from anon, authenticated, service_role, postgres;
grant select on public.email_change_log to authenticated;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.email_change_log to postgres;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.email_change_log to service_role;
revoke all on public.email_change_log_id_seq from anon, authenticated, service_role, postgres;
grant select, update, usage on public.email_change_log_id_seq to authenticated;
grant select, update, usage on public.email_change_log_id_seq to postgres;
grant select, update, usage on public.email_change_log_id_seq to service_role;
revoke all on public.enrollments from anon, authenticated, service_role, postgres;
grant delete, insert, maintain, select, update on public.enrollments to authenticated;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.enrollments to postgres;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.enrollments to service_role;
revoke all on public.entries from anon, authenticated, service_role, postgres;
grant delete, insert, maintain, select, update on public.entries to authenticated;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.entries to postgres;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.entries to service_role;
revoke all on public.evaluation_items from anon, authenticated, service_role, postgres;
grant delete, insert, select, update on public.evaluation_items to authenticated;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.evaluation_items to postgres;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.evaluation_items to service_role;
revoke all on public.evaluation_judge_done from anon, authenticated, service_role, postgres;
grant delete, insert, select on public.evaluation_judge_done to authenticated;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.evaluation_judge_done to postgres;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.evaluation_judge_done to service_role;
revoke all on public.evaluation_reviews from anon, authenticated, service_role, postgres;
grant insert, select, update on public.evaluation_reviews to authenticated;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.evaluation_reviews to postgres;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.evaluation_reviews to service_role;
revoke all on public.evaluation_scores from anon, authenticated, service_role, postgres;
grant insert, select, update on public.evaluation_scores to authenticated;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.evaluation_scores to postgres;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.evaluation_scores to service_role;
revoke all on public.events from anon, authenticated, service_role, postgres;
grant delete, insert, maintain, select, update on public.events to authenticated;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.events to postgres;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.events to service_role;
revoke all on public.export_log from anon, authenticated, service_role, postgres;
grant insert, select on public.export_log to authenticated;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.export_log to postgres;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.export_log to service_role;
revoke all on public.feedback from anon, authenticated, service_role, postgres;
grant delete, insert, maintain, select, update on public.feedback to authenticated;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.feedback to postgres;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.feedback to service_role;
revoke all on public.guardian_consents from anon, authenticated, service_role, postgres;
grant select on public.guardian_consents to authenticated;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.guardian_consents to postgres;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.guardian_consents to service_role;
revoke all on public.import_staging from anon, authenticated, service_role, postgres;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.import_staging to postgres;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.import_staging to service_role;
revoke all on public.item_acquisitions from anon, authenticated, service_role, postgres;
grant select on public.item_acquisitions to authenticated;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.item_acquisitions to postgres;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.item_acquisitions to service_role;
revoke all on public.koen from anon, authenticated, service_role, postgres;
grant delete, insert, select, update on public.koen to authenticated;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.koen to postgres;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.koen to service_role;
revoke all on public.koen_cells from anon, authenticated, service_role, postgres;
grant delete, insert, select, update on public.koen_cells to authenticated;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.koen_cells to postgres;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.koen_cells to service_role;
revoke all on public.koen_kid_contact_reads from anon, authenticated, service_role, postgres;
grant select on public.koen_kid_contact_reads to authenticated;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.koen_kid_contact_reads to postgres;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.koen_kid_contact_reads to service_role;
revoke all on public.koen_kid_contacts from anon, authenticated, service_role, postgres;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.koen_kid_contacts to postgres;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.koen_kid_contacts to service_role;
revoke all on public.koen_kids from anon, authenticated, service_role, postgres;
grant insert, select, update on public.koen_kids to authenticated;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.koen_kids to postgres;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.koen_kids to service_role;
revoke all on public.koen_members from anon, authenticated, service_role, postgres;
grant delete, insert, select, update on public.koen_members to authenticated;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.koen_members to postgres;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.koen_members to service_role;
revoke all on public.koen_rows from anon, authenticated, service_role, postgres;
grant delete, insert, select, update on public.koen_rows to authenticated;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.koen_rows to postgres;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.koen_rows to service_role;
revoke all on public.koen_session_changes from anon, authenticated, service_role, postgres;
grant delete, insert, select, update on public.koen_session_changes to authenticated;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.koen_session_changes to postgres;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.koen_session_changes to service_role;
revoke all on public.koen_sessions from anon, authenticated, service_role, postgres;
grant delete, insert, select, update on public.koen_sessions to authenticated;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.koen_sessions to postgres;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.koen_sessions to service_role;
revoke all on public.koen_slots from anon, authenticated, service_role, postgres;
grant delete, insert, select, update on public.koen_slots to authenticated;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.koen_slots to postgres;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.koen_slots to service_role;
revoke all on public.lesson_ng_dates from anon, authenticated, service_role, postgres;
grant delete, insert, select on public.lesson_ng_dates to authenticated;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.lesson_ng_dates to postgres;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.lesson_ng_dates to service_role;
revoke all on public.lesson_prefs from anon, authenticated, service_role, postgres;
grant delete, insert, select, update on public.lesson_prefs to authenticated;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.lesson_prefs to postgres;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.lesson_prefs to service_role;
revoke all on public.lesson_preset_targets from anon, authenticated, service_role, postgres;
grant delete, insert, select, update on public.lesson_preset_targets to authenticated;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.lesson_preset_targets to postgres;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.lesson_preset_targets to service_role;
revoke all on public.lesson_presets from anon, authenticated, service_role, postgres;
grant delete, insert, select, update on public.lesson_presets to authenticated;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.lesson_presets to postgres;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.lesson_presets to service_role;
revoke all on public.lesson_rounds from anon, authenticated, service_role, postgres;
grant insert, select, update on public.lesson_rounds to authenticated;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.lesson_rounds to postgres;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.lesson_rounds to service_role;
revoke all on public.lessons from anon, authenticated, service_role, postgres;
grant delete, insert, maintain on public.lessons to authenticated;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.lessons to postgres;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.lessons to service_role;
revoke all on public.link_consents from anon, authenticated, service_role, postgres;
grant delete, insert, maintain, select, update on public.link_consents to authenticated;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.link_consents to postgres;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.link_consents to service_role;
revoke all on public.matching_cuts from anon, authenticated, service_role, postgres;
grant delete on public.matching_cuts to authenticated;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.matching_cuts to postgres;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.matching_cuts to service_role;
revoke all on public.matching_reports from anon, authenticated, service_role, postgres;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.matching_reports to postgres;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.matching_reports to service_role;
revoke all on public.memberships from anon, authenticated, service_role, postgres;
grant delete, insert, maintain, select on public.memberships to authenticated;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.memberships to postgres;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.memberships to service_role;
revoke all on public.minor_billing_consents from anon, authenticated, service_role, postgres;
grant insert, maintain, select on public.minor_billing_consents to authenticated;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.minor_billing_consents to postgres;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.minor_billing_consents to service_role;
revoke all on public.monka_read_log from anon, authenticated, service_role, postgres;
grant select on public.monka_read_log to authenticated;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.monka_read_log to postgres;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.monka_read_log to service_role;
revoke all on public.my_periods from anon, authenticated, service_role, postgres;
grant delete, insert, select, update on public.my_periods to authenticated;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.my_periods to postgres;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.my_periods to service_role;
revoke all on public.my_timetable from anon, authenticated, service_role, postgres;
grant delete, insert, select, update on public.my_timetable to authenticated;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.my_timetable to postgres;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.my_timetable to service_role;
revoke all on public.notes from anon, authenticated, service_role, postgres;
grant delete, insert, maintain, select, update on public.notes to authenticated;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.notes to postgres;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.notes to service_role;
revoke all on public.notice_batches from anon, authenticated, service_role, postgres;
grant delete, insert, maintain, select, update on public.notice_batches to authenticated;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.notice_batches to postgres;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.notice_batches to service_role;
revoke all on public.notice_targets from anon, authenticated, service_role, postgres;
grant delete, insert, maintain, select, update on public.notice_targets to authenticated;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.notice_targets to postgres;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.notice_targets to service_role;
revoke all on public.ops_alerts from anon, authenticated, service_role, postgres;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.ops_alerts to postgres;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.ops_alerts to service_role;
revoke all on public.ops_audit_log from anon, authenticated, service_role, postgres;
grant select on public.ops_audit_log to authenticated;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.ops_audit_log to postgres;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.ops_audit_log to service_role;
revoke all on public.org_billing from anon, authenticated, service_role, postgres;
grant insert, select, update on public.org_billing to authenticated;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.org_billing to postgres;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.org_billing to service_role;
revoke all on public.org_billing_log from anon, authenticated, service_role, postgres;
grant insert, select on public.org_billing_log to authenticated;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.org_billing_log to postgres;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.org_billing_log to service_role;
revoke all on public.org_contracts from anon, authenticated, service_role, postgres;
grant select on public.org_contracts to authenticated;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.org_contracts to postgres;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.org_contracts to service_role;
revoke all on public.org_divisions from anon, authenticated, service_role, postgres;
grant delete, insert, select, update on public.org_divisions to authenticated;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.org_divisions to postgres;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.org_divisions to service_role;
revoke all on public.org_event_participants from anon, authenticated, service_role, postgres;
grant delete, insert, maintain, select, update on public.org_event_participants to authenticated;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.org_event_participants to postgres;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.org_event_participants to service_role;
revoke all on public.org_events from anon, authenticated, service_role, postgres;
grant maintain on public.org_events to authenticated;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.org_events to postgres;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.org_events to service_role;
revoke all on public.org_invitations from anon, authenticated, service_role, postgres;
grant delete, insert, maintain, select, update on public.org_invitations to authenticated;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.org_invitations to postgres;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.org_invitations to service_role;
revoke all on public.org_message_drafts from anon, authenticated, service_role, postgres;
grant delete, insert, select, update on public.org_message_drafts to authenticated;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.org_message_drafts to postgres;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.org_message_drafts to service_role;
revoke all on public.org_message_reads from anon, authenticated, service_role, postgres;
grant insert, maintain, select on public.org_message_reads to authenticated;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.org_message_reads to postgres;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.org_message_reads to service_role;
revoke all on public.org_messages from anon, authenticated, service_role, postgres;
grant insert, select on public.org_messages to authenticated;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.org_messages to postgres;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.org_messages to service_role;
revoke all on public.org_periods from anon, authenticated, service_role, postgres;
grant delete, insert, select, update on public.org_periods to authenticated;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.org_periods to postgres;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.org_periods to service_role;
revoke all on public.org_places from anon, authenticated, service_role, postgres;
grant delete, insert, select, update on public.org_places to authenticated;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.org_places to postgres;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.org_places to service_role;
revoke all on public.org_post_perm_log from anon, authenticated, service_role, postgres;
grant select on public.org_post_perm_log to authenticated;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.org_post_perm_log to postgres;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.org_post_perm_log to service_role;
revoke all on public.org_posts from anon, authenticated, service_role, postgres;
grant select on public.org_posts to authenticated;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.org_posts to postgres;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.org_posts to service_role;
revoke all on public.organizations from anon, authenticated, service_role, postgres;
grant delete, insert, maintain, select, update on public.organizations to authenticated;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.organizations to postgres;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.organizations to service_role;
revoke all on public.overlap_notices from anon, authenticated, service_role, postgres;
grant delete, insert, select, update on public.overlap_notices to authenticated;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.overlap_notices to postgres;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.overlap_notices to service_role;
revoke all on public.page_inquiries from anon, authenticated, service_role, postgres;
grant select on public.page_inquiries to authenticated;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.page_inquiries to postgres;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.page_inquiries to service_role;
revoke all on public.page_types_owned from anon, authenticated, service_role, postgres;
grant select on public.page_types_owned to authenticated;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.page_types_owned to postgres;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.page_types_owned to service_role;
revoke all on public.payment_records from anon, authenticated, service_role, postgres;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.payment_records to postgres;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.payment_records to service_role;
revoke all on public.performance_results from anon, authenticated, service_role, postgres;
grant delete, insert, maintain, select, update on public.performance_results to authenticated;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.performance_results to postgres;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.performance_results to service_role;
revoke all on public.performances from anon, authenticated, service_role, postgres;
grant delete, insert, maintain, select, update on public.performances to authenticated;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.performances to postgres;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.performances to service_role;
revoke all on public.period_markers from anon, authenticated, service_role, postgres;
grant delete, insert, select on public.period_markers to authenticated;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.period_markers to postgres;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.period_markers to service_role;
revoke all on public.portfolio_entries from anon, authenticated, service_role, postgres;
grant delete, insert, select, update on public.portfolio_entries to authenticated;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.portfolio_entries to postgres;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.portfolio_entries to service_role;
revoke all on public.portfolio_recordings from anon, authenticated, service_role, postgres;
grant delete, insert, select, update on public.portfolio_recordings to authenticated;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.portfolio_recordings to postgres;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.portfolio_recordings to service_role;
revoke all on public.portfolios from anon, authenticated, service_role, postgres;
grant delete, insert, select, update on public.portfolios to authenticated;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.portfolios to postgres;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.portfolios to service_role;
revoke all on public.post_change_log from anon, authenticated, service_role, postgres;
grant insert, select on public.post_change_log to authenticated;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.post_change_log to postgres;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.post_change_log to service_role;
revoke all on public.postings from anon, authenticated, service_role, postgres;
grant delete on public.postings to authenticated;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.postings to postgres;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.postings to service_role;
revoke all on public.profiles from anon, authenticated, service_role, postgres;
grant insert, maintain, select on public.profiles to authenticated;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.profiles to postgres;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.profiles to service_role;
revoke all on public.project_master from anon, authenticated, service_role, postgres;
grant delete, insert, maintain, select, update on public.project_master to authenticated;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.project_master to postgres;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.project_master to service_role;
revoke all on public.purchases from anon, authenticated, service_role, postgres;
grant maintain, select on public.purchases to authenticated;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.purchases to postgres;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.purchases to service_role;
revoke all on public.questionnaire_responses from anon, authenticated, service_role, postgres;
grant delete, insert, maintain, select, update on public.questionnaire_responses to authenticated;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.questionnaire_responses to postgres;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.questionnaire_responses to service_role;
revoke all on public.recovery_codes from anon, authenticated, service_role, postgres;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.recovery_codes to postgres;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.recovery_codes to service_role;
revoke all on public.repertoire_tessitura from anon, authenticated, service_role, postgres;
grant delete, insert, maintain, select, update on public.repertoire_tessitura to authenticated;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.repertoire_tessitura to postgres;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.repertoire_tessitura to service_role;
revoke all on public.role_master from anon, authenticated, service_role, postgres;
grant delete, insert, maintain, select, update on public.role_master to authenticated;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.role_master to postgres;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.role_master to service_role;
revoke all on public.roster_drafts from anon, authenticated, service_role, postgres;
grant delete, insert, select, update on public.roster_drafts to authenticated;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.roster_drafts to postgres;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.roster_drafts to service_role;
revoke all on public.score_log from anon, authenticated, service_role, postgres;
grant select on public.score_log to authenticated;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.score_log to postgres;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.score_log to service_role;
revoke all on public.stripe_events from anon, authenticated, service_role, postgres;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.stripe_events to postgres;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.stripe_events to service_role;
revoke all on public.student_price_consents from anon, authenticated, service_role, postgres;
grant select on public.student_price_consents to authenticated;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.student_price_consents to postgres;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.student_price_consents to service_role;
revoke all on public.subscription_items from anon, authenticated, service_role, postgres;
grant select on public.subscription_items to authenticated;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.subscription_items to postgres;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.subscription_items to service_role;
revoke all on public.subscriptions from anon, authenticated, service_role, postgres;
grant maintain, select on public.subscriptions to authenticated;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.subscriptions to postgres;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.subscriptions to service_role;
revoke all on public.system_alerts from anon, authenticated, service_role, postgres;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.system_alerts to postgres;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.system_alerts to service_role;
revoke all on public.teacher_invitations from anon, authenticated, service_role, postgres;
grant delete, insert, maintain, select, update on public.teacher_invitations to authenticated;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.teacher_invitations to postgres;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.teacher_invitations to service_role;
revoke all on public.teacher_notes from anon, authenticated, service_role, postgres;
grant delete, insert, maintain, select, update on public.teacher_notes to authenticated;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.teacher_notes to postgres;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.teacher_notes to service_role;
revoke all on public.teacher_student_links from anon, authenticated, service_role, postgres;
grant maintain, select on public.teacher_student_links to authenticated;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.teacher_student_links to postgres;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.teacher_student_links to service_role;
revoke all on public.timetable_nudges from anon, authenticated, service_role, postgres;
grant select on public.timetable_nudges to authenticated;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.timetable_nudges to postgres;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.timetable_nudges to service_role;
revoke all on public.user_notices from anon, authenticated, service_role, postgres;
grant delete, insert, maintain, select, update on public.user_notices to authenticated;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.user_notices to postgres;
grant delete, insert, maintain, references, select, trigger, truncate, update on public.user_notices to service_role;

-- ★★★2 列ごと（25 組）
grant insert (application_id, pieces, sender_user_id, template_key) on public.application_messages to authenticated;
grant select (application_id, created_at, id, pieces, sender_user_id, template_key) on public.application_messages to authenticated;
grant insert (applicant_user_id, available_days, org_id, posting_id, show_career, show_photo, show_recordings, show_repertoire, template_key) on public.applications to authenticated;
grant select (applicant_user_id, available_days, created_at, id, org_id, posting_id, show_career, show_photo, show_recordings, show_repertoire, status, template_key) on public.applications to authenticated;
grant update (available_days, show_career, show_photo, show_recordings, show_repertoire, status) on public.applications to authenticated;
grant update (ended_at) on public.assignments to authenticated;
grant update (grade_label) on public.enrollments to authenticated;
grant select (attendance, attendance_at, attendance_by, created_at, duration_minutes, id, kind, link_id, note, org_id, place_id, scheduled_at, student_id, student_notice, student_notice_at, teacher_id) on public.lessons to authenticated;
grant update (student_notice, student_notice_at) on public.lessons to authenticated;
grant insert (kind, org_id, target_user_id, user_id) on public.matching_cuts to authenticated;
grant select (created_at, id, kind, org_id, target_user_id, user_id) on public.matching_cuts to authenticated;
grant insert (detail, org_id, reason, reporter_user_id, target_user_id) on public.matching_reports to authenticated;
grant select (created_at, detail, id, org_id, reason, target_user_id) on public.matching_reports to authenticated;
grant update (grade_label, role) on public.memberships to authenticated;
grant select (created_at, end_time, event_date, id, kind, org_id, place, previous_date, start_time, target_courses, target_grades, title, updated_at, withdrawn_at) on public.org_events to authenticated;
grant update (end_time, event_date, kind, start_time, title, withdrawn_at) on public.org_events to authenticated;
grant update (withdrawn_at) on public.org_messages to authenticated;
grant insert (morning_words) on public.performances to authenticated;
grant select (morning_words) on public.performances to authenticated;
grant update (morning_words) on public.performances to authenticated;
grant insert (days, expires_at, fee_amount, fee_unit, kind, need_all_days, org_id, owner_user_id, piece, sodan, status, title) on public.postings to authenticated;
grant select (created_at, days, fee_amount, fee_unit, id, kind, need_all_days, org_id, owner_user_id, piece, sodan, status, title) on public.postings to authenticated;
grant update (days, expires_at, fee_amount, fee_unit, kind, need_all_days, piece, sodan, status, title) on public.postings to authenticated;
grant update (age, age_band, age_band_answered_at, age_question_shown_at, allergies, character_equipped, cohort_since, comfort_range_high, comfort_range_low, conditions, consent_health_data_at, consent_health_data_withdrawn_at, consent_policy_version, consent_stats_use_at, created_at, cycle_show_on_home, data_region, day_record_boundary_hour, display_name, display_scale, email, folded_groups, garden_theme, goal_focus, guardian_consent_declared_at, health_notes, height_cm, id, is_under_18, kana, line_link_code, line_linked_at, line_notification_enabled, line_user_id, name, nutrition_phase, occupation, occupation_migrated_from, occupation_notice_shown_at, onboarding_completed, otp_migration_completed_at, otp_migration_declined_at, otp_migration_steps, practice_goal, practice_goal_started_at, practice_goal_tags, practice_reviews, professions, protein_coefficient, pwa_install_prompted_at, pwa_installed_at, record_mode, reflux_care_consent_at, regular_medications, school, sex, simple_display, survey_day7_response, survey_day7_shown_at, technical_goal, track_cycle, vocal_profession, vocal_range_high, vocal_range_low, voice_mix, voice_mix_edited_at, voice_occupation, voice_type) on public.profiles to authenticated;
grant update (revoked_at, revoked_by, status) on public.teacher_student_links to authenticated;

-- ★★★3 関数（99 本）
revoke all on function public._is_enrolled_somewhere(p_user uuid) from public, anon, authenticated, service_role, postgres;
grant execute on function public._is_enrolled_somewhere(p_user uuid) to postgres, service_role;
revoke all on function public.accept_guardian_consent(p_token text) from public, anon, authenticated, service_role, postgres;
grant execute on function public.accept_guardian_consent(p_token text) to anon, authenticated, postgres, service_role;
revoke all on function public.accept_teacher_invitation(p_code text) from public, anon, authenticated, service_role, postgres;
grant execute on function public.accept_teacher_invitation(p_code text) to authenticated, postgres, service_role;
revoke all on function public.admin_entry_stats(p_user_id uuid) from public, anon, authenticated, service_role, postgres;
grant execute on function public.admin_entry_stats(p_user_id uuid) to postgres, service_role;
revoke all on function public.application_party(p_application_id uuid) from public, anon, authenticated, service_role, postgres;
grant execute on function public.application_party(p_application_id uuid) to postgres, service_role;
revoke all on function public.are_connected(viewer_id uuid, other_id uuid) from public, anon, authenticated, service_role, postgres;
grant execute on function public.are_connected(viewer_id uuid, other_id uuid) to authenticated, postgres, service_role;
revoke all on function public.assert_assignment_identity_unchanged() from public, anon, authenticated, service_role, postgres;
grant execute on function public.assert_assignment_identity_unchanged() to anon, authenticated, postgres, public, service_role;
revoke all on function public.assert_lesson_identity_unchanged() from public, anon, authenticated, service_role, postgres;
grant execute on function public.assert_lesson_identity_unchanged() to anon, authenticated, postgres, public, service_role;
revoke all on function public.assert_link_identity_unchanged() from public, anon, authenticated, service_role, postgres;
grant execute on function public.assert_link_identity_unchanged() to anon, authenticated, postgres, public, service_role;
revoke all on function public.assert_my_periods_org_stable() from public, anon, authenticated, service_role, postgres;
grant execute on function public.assert_my_periods_org_stable() to postgres, service_role;
revoke all on function public.assert_org_event_identity_unchanged() from public, anon, authenticated, service_role, postgres;
grant execute on function public.assert_org_event_identity_unchanged() to anon, authenticated, postgres, public, service_role;
revoke all on function public.assert_student_is_adult() from public, anon, authenticated, service_role, postgres;
grant execute on function public.assert_student_is_adult() to postgres, service_role;
revoke all on function public.assignments_old_identity(p_id uuid) from public, anon, authenticated, service_role, postgres;
grant execute on function public.assignments_old_identity(p_id uuid) to authenticated, postgres, service_role;
revoke all on function public.audit_row() from public, anon, authenticated, service_role, postgres;
grant execute on function public.audit_row() to postgres, service_role;
revoke all on function public.can_grant_post(p_org_id uuid, p_post_id uuid) from public, anon, authenticated, service_role, postgres;
grant execute on function public.can_grant_post(p_org_id uuid, p_post_id uuid) to authenticated, postgres, service_role;
revoke all on function public.can_view_ops_perm(viewer_id uuid, p_org_id uuid, p_student_id uuid, p_perm text) from public, anon, authenticated, service_role, postgres;
grant execute on function public.can_view_ops_perm(viewer_id uuid, p_org_id uuid, p_student_id uuid, p_perm text) to authenticated, postgres, service_role;
revoke all on function public.can_view_organization(viewer_id uuid, p_org_id uuid) from public, anon, authenticated, service_role, postgres;
grant execute on function public.can_view_organization(viewer_id uuid, p_org_id uuid) to authenticated, postgres, service_role;
revoke all on function public.change_monka_teacher(p_org_id uuid, p_student_id uuid, p_new_teacher_id uuid) from public, anon, authenticated, service_role, postgres;
grant execute on function public.change_monka_teacher(p_org_id uuid, p_student_id uuid, p_new_teacher_id uuid) to authenticated, postgres, service_role;
revoke all on function public.character_unlock_summary(p_user_id uuid) from public, anon, authenticated, service_role, postgres;
grant execute on function public.character_unlock_summary(p_user_id uuid) to postgres, service_role;
revoke all on function public.choose_applicant(p_application_id uuid) from public, anon, authenticated, service_role, postgres;
grant execute on function public.choose_applicant(p_application_id uuid) to authenticated, postgres, service_role;
revoke all on function public.clear_my_busy_slots() from public, anon, authenticated, service_role, postgres;
grant execute on function public.clear_my_busy_slots() to authenticated, postgres, service_role;
revoke all on function public.confirm_event_scores(p_org_id uuid, p_event_id uuid) from public, anon, authenticated, service_role, postgres;
grant execute on function public.confirm_event_scores(p_org_id uuid, p_event_id uuid) to authenticated, postgres, service_role;
revoke all on function public.consent_withdrawn(p_user uuid) from public, anon, authenticated, service_role, postgres;
grant execute on function public.consent_withdrawn(p_user uuid) to authenticated, postgres, service_role;
revoke all on function public.create_org_event(p_org_id uuid, p_event_date date, p_kind text, p_title text, p_start_time time without time zone, p_end_time time without time zone, p_place text, p_target_grades text[], p_target_courses text[]) from public, anon, authenticated, service_role, postgres;
grant execute on function public.create_org_event(p_org_id uuid, p_event_date date, p_kind text, p_title text, p_start_time time without time zone, p_end_time time without time zone, p_place text, p_target_grades text[], p_target_courses text[]) to authenticated, postgres, service_role;
revoke all on function public.edit_confirmed_score(p_score_id uuid, p_points numeric, p_reason text) from public, anon, authenticated, service_role, postgres;
grant execute on function public.edit_confirmed_score(p_score_id uuid, p_points numeric, p_reason text) to authenticated, postgres, service_role;
revoke all on function public.entries_set_source() from public, anon, authenticated, service_role, postgres;
grant execute on function public.entries_set_source() to anon, authenticated, postgres, public, service_role;
revoke all on function public.evaluation_scores_guard() from public, anon, authenticated, service_role, postgres;
grant execute on function public.evaluation_scores_guard() to postgres, service_role;
revoke all on function public.get_applicant_detail(p_application_id uuid) from public, anon, authenticated, service_role, postgres;
grant execute on function public.get_applicant_detail(p_application_id uuid) to authenticated, postgres, service_role;
revoke all on function public.get_applications(p_posting_id uuid) from public, anon, authenticated, service_role, postgres;
grant execute on function public.get_applications(p_posting_id uuid) to authenticated, postgres, service_role;
revoke all on function public.get_connected_names(p_ids uuid[]) from public, anon, authenticated, service_role, postgres;
grant execute on function public.get_connected_names(p_ids uuid[]) to authenticated, postgres, service_role;
revoke all on function public.get_contract_candidates(p_org_id uuid) from public, anon, authenticated, service_role, postgres;
grant execute on function public.get_contract_candidates(p_org_id uuid) to authenticated, postgres, service_role;
revoke all on function public.get_invitation_teacher(p_code text) from public, anon, authenticated, service_role, postgres;
grant execute on function public.get_invitation_teacher(p_code text) to authenticated, postgres, service_role;
revoke all on function public.get_lesson_preset_for_student(p_org_id uuid) from public, anon, authenticated, service_role, postgres;
grant execute on function public.get_lesson_preset_for_student(p_org_id uuid) to authenticated, postgres, service_role;
revoke all on function public.get_match(p_application_id uuid) from public, anon, authenticated, service_role, postgres;
grant execute on function public.get_match(p_application_id uuid) to authenticated, postgres, service_role;
revoke all on function public.get_messages(p_application_id uuid) from public, anon, authenticated, service_role, postgres;
grant execute on function public.get_messages(p_application_id uuid) to authenticated, postgres, service_role;
revoke all on function public.get_monka_free_counts() from public, anon, authenticated, service_role, postgres;
grant execute on function public.get_monka_free_counts() to authenticated, postgres, service_role;
revoke all on function public.get_monka_read_notices() from public, anon, authenticated, service_role, postgres;
grant execute on function public.get_monka_read_notices() to authenticated, postgres, service_role;
revoke all on function public.get_my_applications() from public, anon, authenticated, service_role, postgres;
grant execute on function public.get_my_applications() to authenticated, postgres, service_role;
revoke all on function public.get_my_busy_slots() from public, anon, authenticated, service_role, postgres;
grant execute on function public.get_my_busy_slots() to authenticated, postgres, service_role;
revoke all on function public.get_my_cuts() from public, anon, authenticated, service_role, postgres;
grant execute on function public.get_my_cuts() to authenticated, postgres, service_role;
revoke all on function public.get_my_monka_invites() from public, anon, authenticated, service_role, postgres;
grant execute on function public.get_my_monka_invites() to authenticated, postgres, service_role;
revoke all on function public.get_my_named_invites(p_org_id uuid) from public, anon, authenticated, service_role, postgres;
grant execute on function public.get_my_named_invites(p_org_id uuid) to authenticated, postgres, service_role;
revoke all on function public.get_my_postings() from public, anon, authenticated, service_role, postgres;
grant execute on function public.get_my_postings() to authenticated, postgres, service_role;
revoke all on function public.get_my_schools() from public, anon, authenticated, service_role, postgres;
grant execute on function public.get_my_schools() to authenticated, postgres, service_role;
revoke all on function public.get_my_teacher_names() from public, anon, authenticated, service_role, postgres;
grant execute on function public.get_my_teacher_names() to authenticated, postgres, service_role;
revoke all on function public.get_org_member_names(p_org_id uuid) from public, anon, authenticated, service_role, postgres;
grant execute on function public.get_org_member_names(p_org_id uuid) to authenticated, postgres, service_role;
revoke all on function public.get_org_student_names(p_org_id uuid) from public, anon, authenticated, service_role, postgres;
grant execute on function public.get_org_student_names(p_org_id uuid) to authenticated, postgres, service_role;
revoke all on function public.get_posting_detail(p_posting_id uuid) from public, anon, authenticated, service_role, postgres;
grant execute on function public.get_posting_detail(p_posting_id uuid) to authenticated, postgres, service_role;
revoke all on function public.get_postings(p_org_id uuid) from public, anon, authenticated, service_role, postgres;
grant execute on function public.get_postings(p_org_id uuid) to authenticated, postgres, service_role;
revoke all on function public.get_public_portfolio(p_slug text) from public, anon, authenticated, service_role, postgres;
grant execute on function public.get_public_portfolio(p_slug text) to anon, authenticated, postgres, service_role;
revoke all on function public.get_student_free_slots(p_org_id uuid, p_user_ids uuid[]) from public, anon, authenticated, service_role, postgres;
grant execute on function public.get_student_free_slots(p_org_id uuid, p_user_ids uuid[]) to authenticated, postgres, service_role;
revoke all on function public.get_teacher_periods(p_org_id uuid, p_teacher_id uuid) from public, anon, authenticated, service_role, postgres;
grant execute on function public.get_teacher_periods(p_org_id uuid, p_teacher_id uuid) to authenticated, postgres, service_role;
revoke all on function public.get_timetable_submitted(p_org_id uuid) from public, anon, authenticated, service_role, postgres;
grant execute on function public.get_timetable_submitted(p_org_id uuid) to authenticated, postgres, service_role;
revoke all on function public.give_student_price_consent(p_text_version text) from public, anon, authenticated, service_role, postgres;
grant execute on function public.give_student_price_consent(p_text_version text) to authenticated, postgres, service_role;
revoke all on function public.guard_enrollment_grade_label() from public, anon, authenticated, service_role, postgres;
grant execute on function public.guard_enrollment_grade_label() to authenticated, postgres, public, service_role;
revoke all on function public.guard_grade_label() from public, anon, authenticated, service_role, postgres;
grant execute on function public.guard_grade_label() to authenticated, postgres, public, service_role;
revoke all on function public.handle_new_user() from public, anon, authenticated, service_role, postgres;
grant execute on function public.handle_new_user() to postgres, service_role;
revoke all on function public.has_can(p_org_id uuid, p_perm text) from public, anon, authenticated, service_role, postgres;
grant execute on function public.has_can(p_org_id uuid, p_perm text) to authenticated, postgres, service_role;
revoke all on function public.has_can_user(p_user_id uuid, p_org_id uuid, p_perm text) from public, anon, authenticated, service_role, postgres;
grant execute on function public.has_can_user(p_user_id uuid, p_org_id uuid, p_perm text) to authenticated, postgres, service_role;
revoke all on function public.has_guardian_consent(p_user_id uuid, p_org_id uuid) from public, anon, authenticated, service_role, postgres;
grant execute on function public.has_guardian_consent(p_user_id uuid, p_org_id uuid) to authenticated, postgres, service_role;
revoke all on function public.is_org_member(viewer_id uuid, p_org_id uuid) from public, anon, authenticated, service_role, postgres;
grant execute on function public.is_org_member(viewer_id uuid, p_org_id uuid) to authenticated, postgres, service_role;
revoke all on function public.koen_can_manage(p_koen uuid) from public, anon, authenticated, service_role, postgres;
grant execute on function public.koen_can_manage(p_koen uuid) to authenticated, postgres, service_role;
revoke all on function public.koen_can_see(p_koen uuid) from public, anon, authenticated, service_role, postgres;
grant execute on function public.koen_can_see(p_koen uuid) to authenticated, postgres, service_role;
revoke all on function public.leave_enrollment(p_org_id uuid) from public, anon, authenticated, service_role, postgres;
grant execute on function public.leave_enrollment(p_org_id uuid) to authenticated, postgres, service_role;
revoke all on function public.log_koen_session_change() from public, anon, authenticated, service_role, postgres;
grant execute on function public.log_koen_session_change() to postgres, service_role;
revoke all on function public.log_org_post_perm() from public, anon, authenticated, service_role, postgres;
grant execute on function public.log_org_post_perm() to postgres, service_role;
revoke all on function public.mark_attendance(p_lesson_id uuid, p_status text) from public, anon, authenticated, service_role, postgres;
grant execute on function public.mark_attendance(p_lesson_id uuid, p_status text) to authenticated, postgres, service_role;
revoke all on function public.matching_report_makes_cut() from public, anon, authenticated, service_role, postgres;
grant execute on function public.matching_report_makes_cut() to postgres, service_role;
revoke all on function public.matching_suspended(p_user uuid) from public, anon, authenticated, service_role, postgres;
grant execute on function public.matching_suspended(p_user uuid) to postgres, service_role;
revoke all on function public.matching_visible(p_viewer uuid, p_target uuid) from public, anon, authenticated, service_role, postgres;
grant execute on function public.matching_visible(p_viewer uuid, p_target uuid) to postgres, service_role;
revoke all on function public.monka_representative_max() from public, anon, authenticated, service_role, postgres;
grant execute on function public.monka_representative_max() to authenticated, postgres, service_role;
revoke all on function public.move_lesson(p_lesson_id uuid, p_scheduled_at timestamp with time zone, p_place_id uuid) from public, anon, authenticated, service_role, postgres;
grant execute on function public.move_lesson(p_lesson_id uuid, p_scheduled_at timestamp with time zone, p_place_id uuid) to authenticated, postgres, service_role;
revoke all on function public.my_entitlements() from public, anon, authenticated, service_role, postgres;
grant execute on function public.my_entitlements() to authenticated, postgres, service_role;
revoke all on function public.nudge_timetable(p_org_id uuid, p_student_ids uuid[]) from public, anon, authenticated, service_role, postgres;
grant execute on function public.nudge_timetable(p_org_id uuid, p_student_ids uuid[]) to authenticated, postgres, service_role;
revoke all on function public.open_monka_thread(p_org_id uuid, p_teacher_id uuid, p_reason_kind text, p_reason_note text) from public, anon, authenticated, service_role, postgres;
grant execute on function public.open_monka_thread(p_org_id uuid, p_teacher_id uuid, p_reason_kind text, p_reason_note text) to authenticated, postgres, service_role;
revoke all on function public.org_events_set_bookkeeping() from public, anon, authenticated, service_role, postgres;
grant execute on function public.org_events_set_bookkeeping() to anon, authenticated, postgres, public, service_role;
revoke all on function public.org_free_period(p_start date, p_is_pilot boolean) from public, anon, authenticated, service_role, postgres;
grant execute on function public.org_free_period(p_start date, p_is_pilot boolean) to authenticated, postgres, public, service_role;
revoke all on function public.pref_map(p_round_id uuid) from public, anon, authenticated, service_role, postgres;
grant execute on function public.pref_map(p_round_id uuid) to authenticated, postgres, service_role;
revoke all on function public.profiles_guard_server_only_columns() from public, anon, authenticated, service_role, postgres;
grant execute on function public.profiles_guard_server_only_columns() to anon, authenticated, postgres, public, service_role;
revoke all on function public.purge_code_attempts() from public, anon, authenticated, service_role, postgres;
grant execute on function public.purge_code_attempts() to postgres, service_role;
revoke all on function public.purge_ops_audit_log() from public, anon, authenticated, service_role, postgres;
grant execute on function public.purge_ops_audit_log() to postgres, service_role;
revoke all on function public.raise_alert(p_kind text, p_detail text) from public, anon, authenticated, service_role, postgres;
grant execute on function public.raise_alert(p_kind text, p_detail text) to postgres, service_role;
revoke all on function public.read_kid_contact(p_kid uuid, p_reason_kind text) from public, anon, authenticated, service_role, postgres;
grant execute on function public.read_kid_contact(p_kid uuid, p_reason_kind text) to authenticated, postgres, service_role;
revoke all on function public.request_guardian_consent(p_org_id uuid, p_teacher_id uuid, p_guardian_email text) from public, anon, authenticated, service_role, postgres;
grant execute on function public.request_guardian_consent(p_org_id uuid, p_teacher_id uuid, p_guardian_email text) to authenticated, postgres, service_role;
revoke all on function public.retire_teacher(p_org_id uuid, p_teacher_id uuid) from public, anon, authenticated, service_role, postgres;
grant execute on function public.retire_teacher(p_org_id uuid, p_teacher_id uuid) to authenticated, postgres, service_role;
revoke all on function public.role_rank(r text) from public, anon, authenticated, service_role, postgres;
grant execute on function public.role_rank(r text) to anon, authenticated, postgres, public, service_role;
revoke all on function public.rotate_calendar_token() from public, anon, authenticated, service_role, postgres;
grant execute on function public.rotate_calendar_token() to authenticated, postgres, service_role;
revoke all on function public.school_wide_perms() from public, anon, authenticated, service_role, postgres;
grant execute on function public.school_wide_perms() to authenticated, postgres, service_role;
revoke all on function public.seed_prefs_from_timetable(p_round_id uuid) from public, anon, authenticated, service_role, postgres;
grant execute on function public.seed_prefs_from_timetable(p_round_id uuid) to authenticated, postgres, service_role;
revoke all on function public.send_message_draft(p_draft_id uuid) from public, anon, authenticated, service_role, postgres;
grant execute on function public.send_message_draft(p_draft_id uuid) to authenticated, postgres, service_role;
revoke all on function public.set_kid_contact(p_kid uuid, p_contact text) from public, anon, authenticated, service_role, postgres;
grant execute on function public.set_kid_contact(p_kid uuid, p_contact text) to authenticated, postgres, service_role;
revoke all on function public.set_member_display_title(p_membership_id uuid, p_title text) from public, anon, authenticated, service_role, postgres;
grant execute on function public.set_member_display_title(p_membership_id uuid, p_title text) to authenticated, postgres, service_role;
revoke all on function public.set_monka_representative(p_assignment_id uuid, p_on boolean) from public, anon, authenticated, service_role, postgres;
grant execute on function public.set_monka_representative(p_assignment_id uuid, p_on boolean) to authenticated, postgres, service_role;
revoke all on function public.set_web_type(p_type_key text) from public, anon, authenticated, service_role, postgres;
grant execute on function public.set_web_type(p_type_key text) to authenticated, postgres, service_role;
revoke all on function public.student_price_eligible(p_user uuid) from public, anon, authenticated, service_role, postgres;
grant execute on function public.student_price_eligible(p_user uuid) to postgres, service_role;
revoke all on function public.submit_inquiry(p_slug text, p_name text, p_email text, p_body text) from public, anon, authenticated, service_role, postgres;
grant execute on function public.submit_inquiry(p_slug text, p_name text, p_email text, p_body text) to anon, authenticated, postgres, service_role;
revoke all on function public.transfer_contract_owner(p_org_id uuid, p_to_user_id uuid) from public, anon, authenticated, service_role, postgres;
grant execute on function public.transfer_contract_owner(p_org_id uuid, p_to_user_id uuid) to authenticated, postgres, service_role;
revoke all on function public.withdraw_guardian_consent(p_org_id uuid) from public, anon, authenticated, service_role, postgres;
grant execute on function public.withdraw_guardian_consent(p_org_id uuid) to authenticated, postgres, service_role;
revoke all on function public.withdraw_student_price_consent() from public, anon, authenticated, service_role, postgres;
grant execute on function public.withdraw_student_price_consent() to authenticated, postgres, service_role;
