-- ★★★土台 ── 註（comment on）
-- ★裁定175 ㋐。★2026-09-23 の 本番（xxjtplvpcneksrofkjmf）の 形を 機械で 書き出した もの。
-- ★★本番には 当てません。★「すでに 当たって いる」と 記録するだけ です。

comment on table public.account_deletions is '消えたアカウントの数を数えるためだけの表。★時刻以外の列を足さないこと。user_id・メールアドレスは入れない。ポリシーは作らない（service_role だけ）。';
comment on table public.age_answer_changes is '年齢の答え（is_under_18）を変えた記録。★行を消さないこと。★IPを保存しないこと。A-5の監査ログとは別。';
comment on table public.code_attempts is '合言葉の試行回数。合言葉そのものは持たない（塩つきハッシュ）。24時間で消す。';
comment on table public.cohort_changes is '群のラベルを変えた記録。★行を消さないこと。★IPを保存しないこと。age_answer_changesと同じ形。';
comment on table public.consent_records is '同意の記録。★行を消さないこと（撤回は withdrawn_at）。★IPを保存しないこと。目的ごとに1行。';
comment on table public.email_change_log is 'メールアドレスを変えた履歴。乗っ取りに気づくための、唯一の手がかり。足すだけ。消さない・上書きしない。IP は持たない（列が無い）。台帳01（削除処理）に登録すること。アカウント削除で cascade で消える。';
comment on table public.events is '行動ログ。★健康の値を入れないこと（計測とユーザー調査仕様 §3.3）。13か月で削除。';
comment on table public.item_acquisitions is 'J05 台帳。いつ・どの道で・そのときの数。足すだけ。持ち物の正は character_inventory。';
comment on table public.lesson_preset_targets is '授業の型を当てている門下（先生）。裁定その90・2026-09-18。';
comment on table public.lesson_presets is '授業の型。年間の回数を決める。作る・消すのは meibo、見るのは monka_write も。裁定その90・2026-09-18。';
comment on table public.minor_billing_consents is '未成年の方が、有料機能に進む前に押した申告の記録。足すだけ。保護者の同意を「得た」記録ではない。「得たと申告された」記録。';
comment on table public.notes is 'ノート（見本⑥）。日付にも記事にもひもづかない、自由な書きもの。';
comment on table public.notice_batches is 'お知らせの束。宛先を決めた時点で凍らせ、以後 cohort を読み直さない。frozen_count は決めた時点の人数で、個々の退会では動かさない。';
comment on table public.notice_targets is 'お知らせの宛先。★決めた時点の id をそのまま保存する。退会で行ごと消える。';
comment on table public.org_billing is '学校の ご請求（裁定 その74・2026-09-18）。payment_records は使いません（org_id が無く結べないため）。';
comment on table public.org_event_participants is '「出ます」の印。中身を持たない。記録（entries）には一切触れない。日付が変わっても、この印を自動で外さないこと（外すと、出るつもりの人が、外れたことに気づけない）。';
comment on table public.org_events is '組織の予定。取り下げは withdrawn_at を入れる。行を消さないこと（消すと、出ると印をつけた人の画面から黙って消える）。';
comment on table public.org_message_reads is '運営の方が門下を開いた記録。誰が・いつ・どの門下を。中身は残しません。「読むだけです」という約束を、確かめられる形にするためのものです。';
comment on table public.org_messages is '門下の連絡。読む道は2本 ── 平常（assignments.ended_at is null）と調査（monka_read・org_id のみ）。裁定その76追補。';
comment on table public.org_post_perm_log is '役職の できること が変わった記録。引き金で残す。update・delete のポリシーを作らない（裁定160）。';
comment on table public.org_posts is '学校ごとの役職と、その役職ができること。役割（owner/admin/…）を置き換える。裁定9月10日夜§7。';
comment on table public.payment_records is '退会後も法律で7年保存する取引の記録。user_id の列を持たない（切り離し済み）。';
comment on table public.period_markers is '区切りマーカー。理由の欄を作らないこと。服薬・受診を記録しない（食事と就寝の設計 §6）。';
comment on table public.post_change_log is '役職を変えた記録（誰が・いつ・誰を）。坂本さんのお決め・2026-09-18。名も残します（役職が消えても読めるように）。';
comment on table public.purchases is '1回払いの 買い切り（1年間 有効な 利用権）。subscriptions とは 別。行を 消さない。終わっても 残す（いつ買って いつまで使えたか を 残すため）。';
comment on table public.recovery_codes is 'メールを失った方が、もう一度入るための控え。ハッシュだけを持つ。元のコードは保存しない。1人1行。出し直すと上書きされ、古いほうはその場で使えなくなる。利用者からは見えない（ポリシー0本＋権限を剥奪）。触るのは route だけ。書き出し（台帳04）には含めない。本人が持っているものであり、こちらの控えではない。';
comment on table public.system_alerts is '止まったことの知らせの控え。1日1通を（kind, sent_on）の一意で守ります。人にひもづきません。書くのは定期処理（service role）だけです。';
comment on table public.user_notices is '一度だけ表示する案内。★汎用の仕組み。notice_key ごとに、出したかどうかを覚える。今後の一度だけの案内に使い回す。';
comment on column public.age_answer_changes.from_value is '変える前の値。★null は「答えていなかった」。';
comment on column public.article_progress.box is '復習の段階。0=未読 1=直後 2=1日 3=7日 4=21日以降。★正答率は持たない（§9-5）。';
comment on column public.assignments.is_representative is '門下代表かどうか。新しい role を作らない（§6-1）。真偽値1つで足ります。';
comment on column public.consent_records.purpose_key is '目的（health.record / health.cycle / health.meal_sleep / research.anonymized）。正はlib/consent.js。';
comment on column public.consent_records.text_hash is '★表示した文面のハッシュ。省略しないこと。文言を変えたあと、誰が何に同意したかを答えられるようにするため。';
comment on column public.consent_records.withdrawn_at is '★撤回した時刻。行は消さない。「撤回した」という事実の記録が要る。';
comment on column public.enrollments.division_id is '生徒の 学科・コース（org_divisions を 指します）。学部は その 上から 出します。';
comment on column public.enrollments.grade_label is '学年の 言い方（学校が 決める 字）。数は grade_year。';
comment on column public.enrollments.grade_year is '学年を 数で。1 / 2 / 3 …。言い方は grade_label。裁定その98追補・2026-09-19。';
comment on column public.enrollments.status is 'active（在籍）／ paused（休会・数える人数に入りません）／ left（退会）。2026-09-19。';
comment on column public.enrollments.student_number is '★学籍番号（学校ごと）。校務システムに 戻す ときの 鍵（★お決め D92・2026-09-20）';
comment on column public.entries.accompaniment is '伴奏。★記録のみ。負荷の計算には使わない。classical/musical/pops のみ表示。';
comment on column public.entries.belly_tight is 'おなかを締めつけていたか。要配慮個人情報。先生には渡しません。';
comment on column public.entries.drank_today is 'その日、お酒を飲んだか。★量は聞かない。夕食タグのアルコールとは別の族。未成年には出さない（サーバー側）。';
comment on column public.entries.head_raised is '頭の側を上げたか。要配慮個人情報。先生には渡しません。';
comment on column public.entries.meal_marks is '食事の印8つ（fat/sweet/spicy/citrus/choco/coffee/soda/alcohol）。null は「本人がまだ直していない」。空配列は「印は無い、と本人が決めた」。正は lib/mealMarks.js。';
comment on column public.entries.morning_edema is '起きたときのむくみ（中核5項目の⑤）。「なし」「少し」「はっきり」の3択。★null は未回答。';
comment on column public.entries.sleep_side is '寝るときの向き。要配慮個人情報。先生には渡しません（lib/shareScope.js）。正は lib/refluxCare.js。';
comment on column public.entries.smoked_today is 'その日、たばこを吸ったか。★本数は聞かない。未成年には出さない（サーバー側）。';
comment on column public.entries.source is 'その記録が いつ書かれたか。live=その日〜翌日23:59 ／ later=それより後 ／ import=まとめて取り込んだもの。NULL は「分からない」（この列より前の記録）。埋めないこと。行ができるときだけ入る。あとから直しても変わらない。';
comment on column public.entries.type_fields is '型ごとの追加項目（歌う/話す/張る）。鍵の正は lib/typeFields.js。★v1では分析に入れない。';
comment on column public.entries.weather_source is '気温・湿度の出どころ。entered=本人が入れた / carried=前の日から引き継いだ / ★null=不明（移行前・未記録）。正は lib/weatherCarry.js。★引き継ぎは3日まで。★carried の日は快適帯の判定を出さない。★carried が半分を超える期間では、絶対湿度を説明変数に使わない。';
comment on column public.evaluation_reviews.judge_name_at is 'そのときの審査員の名前。judge_id は退会で null になる。裁定168 ★2。';
comment on column public.evaluation_scores.judge_name_at is 'そのときの審査員の名前。judge_id は退会で null になる。裁定168 ★2。';
comment on column public.lesson_presets.need_count is '足りるとされる回数。空なら★印を出さない（勝手な線を引かない）。裁定その90のあと・2026-09-19。';
comment on column public.lessons.attendance is '出欠。came / absent / canceled の3つだけ。null は「まだ押していない」。';
comment on column public.lessons.kind is '★種別（学校が 決める 字）。★こちらからの 既定は ありません（★お決め D93）';
comment on column public.lessons.place_id is '★どこで するか（`org_places`）。★消しても レッスンは 残ります（★お決め D93）';
comment on column public.lessons.student_notice is '生徒からの事前の連絡。absent=休みます／late=遅れます／coming=行けるようになりました。理由の欄は作りません（見本⑥）。欄があれば書く人が出て、体調が伝わります。先生おひとりに届きます。門下にも、学校の運営の方にも届きません。';
comment on column public.lessons.student_notice_at is 'いつ伝えたか。取り消し（null に戻す）もできます。';
comment on column public.memberships.grade_label is '学年・コース（例：声楽3年／修士2年／研究生）。学校が決める文字。既定はnull。';
comment on column public.memberships.post_id is '役職。nullは「まだ決めていない」。決まるまではroleが効く（3段目で切り替え）。';
comment on column public.memberships.verified_at is '役職を 学校が 確かめた 日時。空なら「ご自分で 選んだまま」。見本 P_setPost。';
comment on column public.memberships.verified_by is '確かめた 方。';
comment on column public.monka_read_log.post_name_at is 'そのときの役職名。post_id は後から変わるため、名前を写して残す。裁定159 Q2。';
comment on column public.monka_read_log.reason is '確かめた理由。空では書けません（裁定その76）。4文字以上。';
comment on column public.monka_read_log.reason_kind is 'なぜ開いたか。jiko＝事故・苦情の調べ／honnin＝ご本人からの求め／horei＝法令に基づく求め／sonohoka＝その他（短文必須）。裁定159 Q2。';
comment on column public.monka_read_log.target_monka_id is '門下の先生の user id（この蔵では門下は org_messages.teacher_id で決まります）';
comment on column public.monka_read_log.target_name_at is 'そのときの見られた門下の先生の名前。target_monka_id は退会で null になる。裁定161 FX1。';
comment on column public.my_periods.org_id is 'null＝個人のコマ（学校に関係しない）／not null＝その学校でのコマ。裁定151。';
comment on column public.notes.body is '本文。見出しの列は作らない。一覧の見出しは1行目から画面で作る。';
comment on column public.notes.deleted_at is '消した時刻。行は消さない。退会のときだけ、台帳がまとめて消す。';
comment on column public.notes.gained_text is 'できるようになったこと。書かなくてよい';
comment on column public.notes.kind is '稽古 practice ／ レパートリー repertoire ／ 門下 studio ／ 受診用 clinic';
comment on column public.notes.lesson_on is '稽古の日。書いた日（created_at）とは別です';
comment on column public.notes.next_action is '次に自分がすること（1つ）';
comment on column public.notes.repertoire_name is 'みた曲。repertoire_tessitura.repertoire_nameと同じ文字';
comment on column public.notes.said_text is '言われたこと（そのまま）';
comment on column public.notes.source_label is '「○○先生」など。任意。';
comment on column public.notes.teacher_label is 'だれに。自由文字です。先生のidではありません';
comment on column public.notice_batches.type is 'お知らせの種類（consent_renewal / policy_update / feature / maintenance / research）。★この束専用の列を作らないための列。';
comment on column public.notice_targets.sent_at is '送った時刻。★一度だけ入れ、二度と消さない。opened_at で上書きしないこと（送った事実が消えます）。';
comment on column public.org_billing.bill_contact is '請求書の ご担当の お名前';
comment on column public.org_billing.bill_dept is '請求書の 部署（れい：総務課）';
comment on column public.org_events.place is '場所。自由記述。表は作らない（部屋の予約を始めるときに org_places を作り、koma/lessons と同時に繋ぐ）。裁定その89・2026-09-18。';
comment on column public.org_events.previous_date is '日付が変わる前の日付。「◯月◯日から◯月◯日に変わりました」と言うために残す。';
comment on column public.org_events.target_courses is '対象の学科・コース。空の並び＝みなさん。null にしない。裁定その89・2026-09-18。';
comment on column public.org_events.target_grades is '対象の学年。空の並び＝みなさん。null にしない。裁定その89・2026-09-18。';
comment on column public.org_messages.author_name_at is 'そのときの書いた人の名前。author_id は退会で null になる。裁定168 ★3。';
comment on column public.org_messages.target_division_ids is '宛先の 学科・分野（org_divisions）。空＝しぼらない。裁定その89と同じ形。';
comment on column public.org_messages.target_grade_years is '宛先の 学年（数）。空＝しぼらない。';
comment on column public.org_messages.target_user_ids is '名ざしで 足した 方。空＝しぼらない。';
comment on column public.org_messages.teacher_id is 'null なら 学校からのおしらせ。あれば その先生の門下。';
comment on column public.org_messages.teacher_name_at is 'そのときの門下の先生の名前。teacher_id は退会で null になる。裁定168 ★3（Code の追補）。';
comment on column public.org_messages.title is '題（見本 P_write）。無くても かまいません。';
comment on column public.org_messages.withdrawn_at is '取り消した時刻。行は消しません。静かに1行残ります。';
comment on column public.organizations.created_by is '誰が作ったか（過ぎた事実）。null 可。退会した人の教室では null になる。ここを見て権限を決めないこと。権限は memberships.role で判定する。';
comment on column public.performances.morning_words is '本番の朝に、そのまま返す、ご本人のことば。アプリは読まない・要約しない・分析に使わない。書かなくてよい。';
comment on column public.performances.repertoire_name is 'どの曲の本番か。repertoire_tessitura.repertoire_nameと同じ文字';
comment on column public.postings.expires_at is '★期限（★裁定 その130）。★null は「決めない」。★過ぎても 消しません。★一覧（get_postings）から 外れる だけ です。';
comment on column public.profiles.age_band is '年齢の帯。under15 / teen / adult。null は「まだ答えていない」。is_under_18 とは別の答え。移し替えないこと。生年月日は取らない。';
comment on column public.profiles.age_question_shown_at is 'この質問を一度出した時刻。★飛ばした人にも入る。二度と催促しないための目印で、答えの有無ではない。';
comment on column public.profiles.allergies is '薬剤・食物アレルギー。既往症(conditions)とは別。受診用サマリーに使う。';
comment on column public.profiles.cohort is '群のラベル（tester / general / founder）。★継続率を群ごとに分けるために要る。あとから遡れないため配布の前に入れる。★利用者には見せない。課金ではない。正は lib/entitlements.js。';
comment on column public.profiles.consent_health_data_withdrawn_at is '健康の記録の同意を撤回した時刻。null は「撤回していない」。いまの状態は、この列が正（2026-09-03 の決定）。consent_records は歴史を持つ。いまの状態は持たない。';
comment on column public.profiles.cycle_show_on_home is '周期をホームに出すか（§4-3 の3段階の②）。track_cycle が true のときだけ意味を持つ。';
comment on column public.profiles.data_region is 'データの置き場所（EUの下地づくり.md §4-3）。いまは全員 jp。';
comment on column public.profiles.deleted_at is '削除申請の日時。30日間は復元可能。過ぎたら cron が物理削除する。共有は申請時点で即座に切れる。';
comment on column public.profiles.display_scale is '見やすさ: 文字の大きさ（normal / large / xlarge）。★年齢から決めないこと。';
comment on column public.profiles.guardian_consent_declared_at is '保護者の同意を得た、と申告された時刻。null は未申告。得たかどうかは分からない。申告されたことだけが分かる。これを判断の根拠にしないこと。';
comment on column public.profiles.is_internal is '運営が動作確認のために作った器なら true。お知らせの人数から外すためだけに使う。削除・バックアップ・書き出しの対象からは外さない。1件ずつメールアドレスを確かめて手で立てる。';
comment on column public.profiles.is_tester is 'テスターの印。★課金ではない。仕上がった機能を先に見せるための印で、それ以外の人には「開発中」と出る。正は lib/entitlements.js。is_admin と同じく手で立てる。';
comment on column public.profiles.is_under_18 is '18歳未満か。★null は「まだ答えていない」。既定値を入れないこと。null と true はどちらも未成年として扱う（lib/ageGate.js）。';
comment on column public.profiles.kana is '★氏名カナ。★ご本人が 入れます。★並べ替えに 使います（★お決め D94）';
comment on column public.profiles.occupation is '職業を声の型で切り直す.mdの11種類（classical/musical/pops/voiceActor/narrator/announcer/actorStage/actorScreen/rakugo/mc/other）。v1では計算に未使用。';
comment on column public.profiles.occupation_migrated_from is '移行元のvocal_profession値の記録。singer→classicalの移行対象を後から追跡できるようにするため。';
comment on column public.profiles.occupation_notice_shown_at is '呼び方が変わったことを知らせた時刻。★1回だけ出すこと。';
comment on column public.profiles.otp_migration_completed_at is '6桁への移行を終えた日。片道。パスワードには戻さない。';
comment on column public.profiles.otp_migration_declined_at is '6桁への移行を、お断りになった日。入っていたら、二度とお誘いしない（催促しない）。';
comment on column public.profiles.otp_migration_steps is '移行のどこまで進んだか。復旧コードを渡すのが先、パスワードを外すのが後。drop_password だけ入って recovery_code が無い状態を作らないこと。';
comment on column public.profiles.reauth_at is '大事な操作の前に、もう一度確かめた時刻。サーバだけが書く。クライアントの印は持たせない。5分より前なら、もう一度は求めない。';
comment on column public.profiles.reflux_care_consent_at is '寝るときの姿勢と締めつけの記録に、同意を受け取った日時。null なら記録させません。要配慮個人情報。正は lib/refluxCare.js。';
comment on column public.profiles.regular_medications is '常用薬のリスト（恒久）。その日に飲んだ薬は entries.medication_tags 側で、別物。';
comment on column public.profiles.simple_display is '見やすさ: かんたん表示。★文字の大きさとは独立した設定。';
comment on column public.profiles.voice_mix is '{sing, speak, project}の配合（合計10）。既定はDEFAULT_MIX[occupation]。本人が調整可能。v1では計算に未使用。';
comment on column public.profiles.voice_mix_edited_at is '配合を本人が最後に編集した日時。nullなら既定値のまま。';
comment on column public.profiles.voice_occupation is '声の使い方で分けた職業（11種）。★呼び名と配合の正は lib/occupation.js。
   ★登録画面の自由記述 profiles.occupation とは別の列です。混同しないこと。
   ★v1では分析の説明変数に使わないこと。本人が選ぶまで null。';
comment on column public.repertoire_tessitura.bottom_note is 'いちばん低い音。tessitura_note（まん中）とは別です';
comment on column public.repertoire_tessitura.composer is '作曲家';
comment on column public.repertoire_tessitura.position_in is '役・曲集の中の位置';
comment on column public.repertoire_tessitura.status is 'ようす。4つのどれか（下のcheck）';
comment on column public.repertoire_tessitura.tessitura_note is 'テッシトゥーラ。★任意。画面にも「（任意）」と書いてある。NOT NULL に戻さないこと。歌唱言語だけを先に登録できなくなる。';
comment on column public.subscriptions.contracted_price_yen is '契約したときに実際に請求された額（税込・円）。未成年に売る形 §10「表示していた価格」。プランの表の数字ではなく、Stripe の item の金額を入れる。表を書き換えても、契約の記録は変わってはいけない。';
comment on column public.subscriptions.plan is '契約したプラン。monthly / annual。lib/plans.js の名前と同じ文字列。webhook が、契約時の metadata から入れる。価格から逆算しない。';
comment on column public.teacher_invitations.division_id is '招く ときに 決めて おく 学科・分野。入った ときに enrollments へ 写します。';
comment on column public.teacher_invitations.grade_year is '招く ときに 決めて おく 学年（数）。入った ときに enrollments へ 写します。';
comment on column public.teacher_invitations.invited_at is '★名指しで 出した 時刻。★「招待中」の 表示に 使います';
comment on column public.teacher_invitations.kind is '★`open`（合言葉を 見せる）／`named`（名簿から 招く）';
comment on column public.teacher_invitations.monka_teacher_id is '門下の先生（null なら学校だけ）。teacher_id＝出した方とは別。裁定その83訂正・2026-09-18。';
comment on column public.teacher_invitations.org_id is 'この招待が、どの教室への招待か。発行時に入れる。nullは「発行時には記録していなかった古い招待」。受け取る側で解決する。生徒に先生のmembershipsを読ませないために存在する列（2026-09-01）。';
comment on column public.teacher_invitations.target_user_id is '★名指しの 招きの 宛て先。★`open` の ときは null（★裁定 その108）';
comment on column public.teacher_student_links.share_scope is '2026-09-01 に廃止。共有範囲という考え方そのものを無くしたので、これから先ここに値は入らない。参照して何かを見せないこと。列を残しているのは、過去に何があったかの手がかりのため。';
comment on function public.admin_entry_stats(p_user_id uuid) is '管理画面の入力率と人ごとの件数。数だけを返す。p_user_id が is_admin でなければ null。service_role のみ（No.024）。';
comment on function public.assert_my_periods_org_stable() is 'my_periods.org_id を更新で動かさせない。裁定151 Q3。決まり（RLS）は古い値と新しい値を見比べられないため引き金にしている。';
comment on function public.assert_student_is_adult() is '★未成年（および年齢未回答）のアカウントを、教師との紐付けから弾く。判断の回答 §7-2②。security definerにしているのは、service_roleも必ず通すため。保護者同意ができるまでの措置であり、A-7の残りを不要にするものではない。';
comment on function public.can_grant_post(p_org_id uuid, p_post_id uuid) is '★その役職を、いま自分が渡せるか。★自分が持っていない全校権限は渡せない（★§7-4）。★2026-09-11。';
comment on function public.can_view_ops_perm(viewer_id uuid, p_org_id uuid, p_student_id uuid, p_perm text) is '運営の門。できこと（has_can）と受け持ちで通す。裁定その86・2026-09-18。';
comment on function public.character_unlock_summary(p_user_id uuid) is 'ごほうびの開き方を決める3つの数だけを返します。記録の中身は返しません。service_role だけが呼べます（No.019.5・裁定その61）。';
comment on function public.clear_my_busy_slots() is '★ご自分の「来られない」の 印を まとめて 外す（裁定142）。★auth.uid() の 行 だけ。★人を 引数で 指せない。';
comment on function public.consent_withdrawn(p_user uuid) is '健康の記録の同意を撤回しているか。null は「撤回していない」＝ false。security definer は、ポリシーの中から自分以外の行を見ないためにsearch_path を固定したうえで使っています。見るのは渡された1人ぶんだけです。';
comment on function public.get_applications(p_posting_id uuid) is '★応募の 一覧（★見本 SC[応募を選ぶ]）。★応募の 順。★実績の 順に しません。★学んだ ところは、★ご本人が 見せると 選んだ ときだけ。';
comment on function public.get_contract_candidates(p_org_id uuid) is '契約を 引き継げる 方（master を 持つ 在籍者）を 返す。呼べるのは その 学校の 契約者 だけ。裁定その116・2026-09-20。';
comment on function public.get_monka_free_counts() is '自分の門下の「空きコマの数」だけを返す。どの時間かは返さない。2026-09-19。';
comment on function public.get_monka_read_notices() is '確かめられた日づけと先生の名だけを返します。誰が見たかは返しません（裁定その76）。';
comment on function public.get_my_cuts() is '★自分が 切った 相手の 一覧（★見本「見えなくした 方」）。★ご本人 だけ。★相手にも 運営にも 道は ありません。';
comment on function public.get_my_schools() is '★在籍して いる 学校（★active だけ）。★並びは 入った 順（★裁定 その140）。';
comment on function public.get_org_student_names(p_org_id uuid) is '学校の 生徒の お名前と よみ だけ を 返す。門は レッスンが 見える のと 同じ。2026-09-20。';
comment on function public.get_postings(p_org_id uuid) is '★募集の 一覧（★裁定 その122）。★在籍と 切れて いない ことで 絞ります。★時間・会場・合わせの 場所は 返しません（★裁定 その94 §4g never_show）。';
comment on function public.get_student_free_slots(p_org_id uuid, p_user_ids uuid[]) is '空いているかどうかの2値だけを、まとめて返す。中身は返さない。門は sched_all か 担当の先生本人。裁定その98・2026-09-19。';
comment on function public.get_teacher_periods(p_org_id uuid, p_teacher_id uuid) is '先生の コマ（番号と 時間の 割り方）だけ を 返す。何の 授業かは 返さない。門は sched_all か ご本人。裁定その99 F1・2026-09-19／番号を足した 2026-09-20。';
comment on function public.has_can(p_org_id uuid, p_perm text) is '★その方が、その教室で、その「できること」を持っているか。★役職（org_posts.perms）だけを見る。★role は見ない。★2026-09-11・作業指示 §7-3。';
comment on function public.has_can_user(p_user_id uuid, p_org_id uuid, p_perm text) is 'その人がそのできことを持つか。has_can は auth.uid() 版。裁定その86・2026-09-18。';
comment on function public.leave_enrollment(p_org_id uuid) is '生徒が自分の在籍を left にし、同じ取引で受け持ち（assignments）も閉じる。列を絞るため policy ではなく関数で行う。返り値は在籍の更新行数。';
comment on function public.log_org_post_perm() is 'org_posts の perms・名前が変わったときに1行残す。裁定160。呼ぶ側に任せない。';
comment on function public.mark_attendance(p_lesson_id uuid, p_status text) is '出欠を つける 道。門は has_can(org, shukketsu)。裁定その115 Q1・2026-09-20。';
comment on function public.matching_visible(p_viewer uuid, p_target uuid) is '★切れて いないか（★双方向）＋ ★止まって いないか。★裁定 その121・その125。★通報の 組は matching_cuts の kind=reported が 持ちます。';
comment on function public.move_lesson(p_lesson_id uuid, p_scheduled_at timestamp with time zone, p_place_id uuid) is 'コマの 時刻と 場所 だけ を 動かす。門は sched_all か、ご自分の コマの sched_mine。通らない ときは 0行。2026-09-20・裁定 その108 ③。';
comment on function public.open_monka_thread(p_org_id uuid, p_teacher_id uuid, p_reason_kind text, p_reason_note text) is '門下のやりとりを開く。先に monka_read_log へ1行書き、書けたときだけ中身を返す（fail closed）。理由が無ければ開かない。裁定159 S2。';
comment on function public.profiles_guard_server_only_columns() is '本人に書かせてはいけない列を止める。RLS は行しか絞れず、表ごとの UPDATE grant があるため、列は引き金で止める。止めるのは anon と authenticated だけ。service_role と postgres は通す。列を足すときは components/tests/profiles-server-only.test.js も直すこと。';
comment on function public.school_wide_perms() is '★学校ぜんぶに かかる できこと。★lib/opsPerms.js の schoolWide:true と 同じ。★2026-09-11。';
